import type { ReelScriptSeed } from "../schemas/reelScriptSeed.schema.js";

export const VERSUS_FACEOFF_SEEDS: readonly ReelScriptSeed[] = [
  {
    id: "vf_arena_clash",
    archetype: "versus_faceoff",
    name: "Arena Clash",
    tagline: "Head-to-head combat arena showdown",
    narrative_intent: "Presents both contenders as rivals entering a high-energy combat arena, escalating tension through direct confrontation.",
    visual_staging_guidance: "Split 9:16 frame or rapid cutbacks between contenders with dynamic sparks and arena lighting.",
    segment_beats: {
      segment_1: "Introduce the two contenders vividly like prize fighters entering the arena. Display the question cue.",
      segment_2: "Escalate the clash with action, special moves, or direct comparison of raw power. Build viewer anticipation.",
      segment_3: "Deliver the decisive knockout blow declaring the undisputed winner matching the answer cue, followed by explanation.",
    },
    pacing_tone: "High adrenaline, aggressive sports commentator cadence, intense build-up.",
    preferred_ending_motifs: ["VOTE_FOR_NEXT_DUEL", "TWO_SIDED_DEBATE", "MASCOT_SIGNATURE_PAYOFF"],
  },
  {
    id: "vf_tale_of_the_tape",
    archetype: "versus_faceoff",
    name: "Tale of the Tape",
    tagline: "Metric-by-metric analytical breakdown",
    narrative_intent: "Examines cold hard specs, stats, and tactical traits of both sides before revealing the game-changing deciding factor.",
    visual_staging_guidance: "HUD graphic overlays, sleek technical comparison cards, clean split-screen data metrics.",
    segment_beats: {
      segment_1: "State the head-to-head matchup and display starting stat baselines for both sides with the question cue.",
      segment_2: "Break down strengths and weaknesses, highlighting one counter-intuitive variable that disrupts the balance.",
      segment_3: "Reveal which contender claims victory on the decisive metric matching the answer cue, backed by clear rationale.",
    },
    pacing_tone: "Analytical, crisp, professional tactical breakdown with rhythmic transitions.",
    preferred_ending_motifs: ["TWO_SIDED_DEBATE", "HONEST_CONFESSION", "MASCOT_SIGNATURE_PAYOFF"],
  },
  {
    id: "vf_david_vs_goliath",
    archetype: "versus_faceoff",
    name: "David vs. Goliath",
    tagline: "Overwhelming giant vs. cunning underdog",
    narrative_intent: "Frames the matchup as a classic power imbalance where sheer size/reputation clashes against agility, speed, or surprise advantage.",
    visual_staging_guidance: "Low-angle framing highlighting scale disparity, shifting to dynamic close-ups during the counter-attack.",
    segment_beats: {
      segment_1: "Establish the colossal advantage of the heavy favorite vs. the apparent vulnerability of the challenger with the question cue.",
      segment_2: "Demonstrate the surprising resilience or secret weapon of the underdog, creating high suspense.",
      segment_3: "Deliver the shocking or definitive outcome matching the answer cue, proving why assumptions were right or wrong.",
    },
    pacing_tone: "Dramatic cinematic suspense shifting into an electrifying climax.",
    preferred_ending_motifs: ["HONEST_CONFESSION", "TWO_SIDED_DEBATE", "MASCOT_COMIC_TWIST"],
  },
  {
    id: "vf_simulation_challenge",
    archetype: "versus_faceoff",
    name: "Simulation Challenge",
    tagline: "Simulated stress-test and survival scenario",
    narrative_intent: "Places both contenders in a grueling real-world trial, obstacle course, or extreme environmental test.",
    visual_staging_guidance: "Simulated sandbox or harsh terrain setting with telemetry meters and environmental hazard elements.",
    segment_beats: {
      segment_1: "Set up the extreme environmental trial and present the two subjects facing it with the question cue.",
      segment_2: "Subject both contenders to the heat of the trial, watching who cracks under pressure and who pushes through.",
      segment_3: "Crown the survivor who withstood the trial matching the answer cue with punchy scientific or lore explanation.",
    },
    pacing_tone: "Expeditionary, high-stakes documentary pacing with urgent suspense.",
    preferred_ending_motifs: ["VOTE_FOR_NEXT_DUEL", "MASCOT_SIGNATURE_PAYOFF", "HONEST_CONFESSION"],
  },
];

export const DEEP_TRIVIA_SEEDS: readonly ReelScriptSeed[] = [
  {
    id: "dt_mystery_investigation",
    archetype: "deep_trivia",
    name: "Mystery Investigation",
    tagline: "Forensic clues and detective deduction",
    narrative_intent: "Hooks the audience with a bizarre phenomenon or historical anomaly, piecing together curious clues to solve the mystery.",
    visual_staging_guidance: "Noir detective lighting, magnifying focus, clue board pinning, dramatic zoom on evidence.",
    segment_beats: {
      segment_1: "Hook the viewer with an intriguing, bizarre, or counter-intuitive premise. Pose the dilemma with the question cue.",
      segment_2: "Inspect two forensic clues that narrow down the suspects, inviting the audience to lock in their deduction.",
      segment_3: "Unmask the surprising truth matching the answer cue with a concise, mind-opening explanation.",
    },
    pacing_tone: "Curious, intriguing, investigative whisper building into a eureka revelation.",
    preferred_ending_motifs: ["HONEST_CONFESSION", "TWO_SIDED_DEBATE", "MASCOT_SIGNATURE_PAYOFF"],
  },
  {
    id: "dt_counter_intuitive_trap",
    archetype: "deep_trivia",
    name: "Counter-Intuitive Trap",
    tagline: "The cognitive illusion 90% get wrong",
    narrative_intent: "Calls out common human instinct or popular assumption, exposing why the intuitive answer is actually an ingenious trap.",
    visual_staging_guidance: "Illusionist style framing, visual paradox graphics, dynamic spotlight shifting from false lead to truth.",
    segment_beats: {
      segment_1: "Challenge the viewer with a premise where common sense tempts them toward the wrong answer. Display the question cue.",
      segment_2: "Dismantle the tempting trap option and highlight the subtle twist that confuses most people.",
      segment_3: "Drop the jaw-dropping real answer matching the answer cue with a satisfying 'aha!' explanation.",
    },
    pacing_tone: "Playfully provocative, teasing, fast-paced mental challenge.",
    preferred_ending_motifs: ["HONEST_CONFESSION", "MASCOT_COMIC_TWIST", "MASCOT_SIGNATURE_PAYOFF"],
  },
  {
    id: "dt_elimination_showdown",
    archetype: "deep_trivia",
    name: "Elimination Showdown",
    tagline: "Tension-filled step-by-step choice elimination",
    narrative_intent: "Places the three options on display and systematically crosses off deceptive decoys under a ticking clock.",
    visual_staging_guidance: "Three visual cards or glowing pods in vertical 9:16 layout, turning red as decoys are eliminated.",
    segment_beats: {
      segment_1: "Present the three candidate options on screen with high energy and pose the question cue.",
      segment_2: "Eliminate the first decoy with a sharp fact, leaving two contenders as the countdown accelerates.",
      segment_3: "Shatter the final decoy and illuminate the winning choice matching the answer cue with celebratory fanfare.",
    },
    pacing_tone: "Rhythmic game-show suspense with a ticking clock pulse.",
    preferred_ending_motifs: ["HONEST_CONFESSION", "VOTE_FOR_NEXT_DUEL", "MASCOT_SIGNATURE_PAYOFF"],
  },
  {
    id: "dt_origin_flashback",
    archetype: "deep_trivia",
    name: "Origin Flashback",
    tagline: "Untold origin story and historical revelation",
    narrative_intent: "Transports the viewer back in time to the unexpected genesis of a famous concept, device, or creature.",
    visual_staging_guidance: "Vignette border effect, atmospheric sepia or time-warp distortion, transitioning to vivid clarity on reveal.",
    segment_beats: {
      segment_1: "Pose a question about where an iconic thing truly originated, defying conventional folklore. Display question cue.",
      segment_2: "Rewind into the historical moment or evolutionary turning point that sparked the phenomenon.",
      segment_3: "Reveal the authentic origin matching the answer cue with a memorable piece of historical trivia.",
    },
    pacing_tone: "Storyteller cadence, cinematic grandeur, inspiring discovery.",
    preferred_ending_motifs: ["TWO_SIDED_DEBATE", "MASCOT_SIGNATURE_PAYOFF", "HONEST_CONFESSION"],
  },
];

export const TRUE_FALSE_SEEDS: readonly ReelScriptSeed[] = [
  {
    id: "tf_mythbusters_lab",
    archetype: "verdict_true_false",
    name: "MythBusters Lab",
    tagline: "Scientific testing and the big stamp verdict",
    narrative_intent: "Treats a widespread viral claim as a scientific hypothesis and puts it through a rigorous laboratory trial.",
    visual_staging_guidance: "Laboratory workbench, beaker/gear props, danger warning tape, ending with a massive BUSTED or CONFIRMED stamp graphic.",
    segment_beats: {
      segment_1: "Cite a famous internet rumor or old wives' tale as the test subject. Display the question cue.",
      segment_2: "Run the experiment or examine empirical data, watching whether the claim holds water under pressure.",
      segment_3: "Stamp the final verdict (BUSTED or CONFIRMED) matching the answer cue with concise physical or scientific evidence.",
    },
    pacing_tone: "Energetic, quirky science host, dramatic explosion of confirmation/busting.",
    preferred_ending_motifs: ["HONEST_CONFESSION", "MASCOT_COMIC_TWIST", "MASCOT_SIGNATURE_PAYOFF"],
  },
  {
    id: "tf_everyday_deception",
    archetype: "verdict_true_false",
    name: "Everyday Deception",
    tagline: "Exposing the lie you believed your entire life",
    narrative_intent: "Directly confronts everyday habits, health myths, or school misconceptions that almost everybody assumes are true.",
    visual_staging_guidance: "Relatable everyday setting suddenly disrupted, freeze-frame inspection with bold contrast lighting.",
    segment_beats: {
      segment_1: "Directly ask if the viewer has been believing a lifelong misconception. Display the question cue.",
      segment_2: "Expose where the misleading idea originally came from and why everyone fell for it.",
      segment_3: "Deliver the definitive True/False verdict matching the answer cue, liberating the audience with the real truth.",
    },
    pacing_tone: "Conspiratorial yet informative, mind-opening, conversational empathy.",
    preferred_ending_motifs: ["HONEST_CONFESSION", "TWO_SIDED_DEBATE", "MASCOT_SIGNATURE_PAYOFF"],
  },
  {
    id: "tf_courtroom_verdict",
    archetype: "verdict_true_false",
    name: "Courtroom Verdict",
    tagline: "High-drama trial with gavel-slamming justice",
    narrative_intent: "Puts the controversial statement on trial before the jury of viewers, presenting Exhibit A and Exhibit B before slamming the gavel.",
    visual_staging_guidance: "Courtroom bench, judge's gavel, dramatic spotlight on witness stand, legal verdict banner.",
    segment_beats: {
      segment_1: "Read the charges: a viral statement stands accused of being complete fiction. Display the question cue.",
      segment_2: "Present key Exhibit evidence for and against the claim while the jury decides their stance.",
      segment_3: "Slam the gavel and announce the verdict matching the answer cue with an unassailable summary statement.",
    },
    pacing_tone: "Theatrical courtroom drama, intense gavel slams, authoritative cadence.",
    preferred_ending_motifs: ["HONEST_CONFESSION", "TWO_SIDED_DEBATE", "MASCOT_SIGNATURE_PAYOFF"],
  },
  {
    id: "tf_extreme_fact_check",
    archetype: "verdict_true_false",
    name: "Extreme Fact-Check",
    tagline: "Rapid-fire extreme stress test of wild claims",
    narrative_intent: "Tackles an extreme or unbelievable claim and tests its validity against the harshest laws of nature or records.",
    visual_staging_guidance: "Fast digital telemetry HUD, stopwatch graphics, rapid zoom cuts between claim and extreme benchmark.",
    segment_beats: {
      segment_1: "Present an outrageous claim that sounds impossible on first listen. Display the question cue.",
      segment_2: "Push the claim to its absolute extreme limit to see if reality breaks or holds up.",
      segment_3: "Drop the final verdict matching the answer cue with an unforgettable fact about how extreme reality truly is.",
    },
    pacing_tone: "High speed, urgent, fact-checked intensity with crisp delivery.",
    preferred_ending_motifs: ["VOTE_FOR_NEXT_DUEL", "MASCOT_SIGNATURE_PAYOFF", "HONEST_CONFESSION"],
  },
];

export const ALL_REEL_SCRIPT_SEEDS: readonly ReelScriptSeed[] = [
  ...VERSUS_FACEOFF_SEEDS,
  ...DEEP_TRIVIA_SEEDS,
  ...TRUE_FALSE_SEEDS,
];
