packages:
  - apps/*
  - packages/*
allowBuilds:
  "@google/genai": false
  esbuild: true
  onnxruntime-node: false
  protobufjs: false
  puppeteer: false
  sharp: false
minimumReleaseAgeExclude:
  - hyperframes@0.8.111
  - '@hyperframes/core@0.8.111'
  - '@hyperframes/engine@0.8.111'
  - '@hyperframes/lint@0.8.111'
  - '@hyperframes/parsers@0.8.111'
  - '@hyperframes/producer@0.8.111'
  - '@hyperframes/studio-server@0.8.111'
overrides:
  "@hyperframes/core": "0.8.111"
  "@hyperframes/engine": "0.8.111"
  "@hyperframes/lint": "0.8.111"
  "@hyperframes/parsers": "0.8.111"
  "@hyperframes/studio-server": "0.8.111"
