packages:
  - apps/*
  - packages/*
allowBuilds:
  "@google/genai": false
  esbuild: true
  onnxruntime-node: false
  protobufjs: false
  puppeteer: false
  sharp: false
minimumReleaseAgeExclude:
  - hyperframes@0.8.17
overrides:
  "@hyperframes/core": "0.8.17"
  "@hyperframes/engine": "0.8.17"
  "@hyperframes/lint": "0.8.17"
  "@hyperframes/parsers": "0.8.17"
  "@hyperframes/studio-server": "0.8.17"
