import { calculateThinkingBarTiming, type ThinkingBarRenderInput, type ThinkingBarVariant } from "../types.js";

const CRYSTAL_ORB_SVG = `<svg class="capsule-orb-svg" viewBox="0 0 180 180" aria-hidden="true" data-layout-ignore><defs><radialGradient id="manaAuraGrad" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="rgba(0,240,255,0.45)" /><stop offset="65%" stop-color="rgba(112,0,255,0.2)" /><stop offset="100%" stop-color="rgba(0,0,0,0)" /></radialGradient><linearGradient id="chromeRingGrad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#FFFFFF" /><stop offset="35%" stop-color="#CBD5E1" /><stop offset="70%" stop-color="#00F0FF" /><stop offset="100%" stop-color="#334155" /></linearGradient><radialGradient id="crystalChamberAperture" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="#020914" /><stop offset="75%" stop-color="#041830" /><stop offset="100%" stop-color="#072B54" /></radialGradient><linearGradient id="specularDomeGlare" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="rgba(255,255,255,0.85)" /><stop offset="60%" stop-color="rgba(255,255,255,0.25)" /><stop offset="100%" stop-color="rgba(255,255,255,0)" /></linearGradient></defs><circle cx="90" cy="90" r="84" fill="url(#manaAuraGrad)" /><circle cx="90" cy="90" r="64" fill="#040F22" stroke="url(#chromeRingGrad)" stroke-width="6" filter="drop-shadow(0 0 16px rgba(0,240,255,0.85))" /><circle cx="90" cy="90" r="48" fill="url(#crystalChamberAperture)" stroke="#00F0FF" stroke-width="3.5" /><path d="M54 70 C58 52 72 46 90 46 C108 46 122 52 126 70 C112 60 68 60 54 70 Z" fill="url(#specularDomeGlare)" /><circle cx="90" cy="28" r="3.5" fill="#00FF9D" /><circle cx="90" cy="152" r="3.5" fill="#00FF9D" /><circle cx="28" cy="90" r="3.5" fill="#00FF9D" /><circle cx="152" cy="90" r="3.5" fill="#00FF9D" /><circle cx="68" cy="114" r="4" fill="rgba(255,255,255,0.7)" /><circle cx="114" cy="110" r="3" fill="rgba(0,240,255,0.8)" /></svg>`;

export const capsuleLiquidVariant: ThinkingBarVariant = {
  id: "capsule_liquid",
  displayName: "Neon Jelly Liquid",
  description: "Glowing translucent capsule filled with bubbling neon fluid draining down with dynamic color shift.",
  renderHtml(input: ThinkingBarRenderInput): string {
    const timing = calculateThinkingBarTiming(input);
    return `<div class="thinking-bar thinking-bar-capsule-liquid" ${timing.styleAttr}><div class="capsule-track" aria-label="Quiz liquid timer" data-layout-allow-overflow><div class="capsule-metal-cap cap-left" data-layout-ignore aria-hidden="true"><span class="cap-rivet"></span></div><div class="capsule-glass-chamber"><div class="capsule-liquid-fill"><div class="liquid-wave-front"></div><div class="liquid-bubbles" data-layout-ignore aria-hidden="true"><span class="bub bub-1"></span><span class="bub bub-2"></span><span class="bub bub-3"></span><span class="bub bub-4"></span><span class="bub bub-5"></span></div></div><div class="flask-volume-ticks" data-layout-ignore aria-hidden="true"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div><div class="capsule-glass-glare" data-layout-ignore aria-hidden="true"></div><div class="capsule-bottom-reflection" data-layout-ignore aria-hidden="true"></div></div><div class="capsule-metal-cap cap-right" data-layout-ignore aria-hidden="true"><span class="cap-rivet"></span></div><span class="capsule-timer-marker" data-layout-allow-occlusion data-layout-allow-overlap>${CRYSTAL_ORB_SVG}<div class="mana-sparkles-fx" data-layout-ignore aria-hidden="true"><i>✦</i><i>•</i><i>✦</i></div><b class="marker-val val-query" data-layout-allow-overlap>?</b><b class="marker-val val-5" data-layout-allow-overlap>5</b><b class="marker-val val-4" data-layout-allow-overlap>4</b><b class="marker-val val-3" data-layout-allow-overlap>3</b><b class="marker-val val-2" data-layout-allow-overlap>2</b><b class="marker-val val-1" data-layout-allow-overlap>1</b></span></div></div>`;
  },
  renderCss(): string {
    return `
.thinking-bar-capsule-liquid .capsule-track { position: relative; z-index: 0; width: 100%; height: 64px; overflow: visible; display: flex; align-items: center; border-radius: 9999px; background: rgba(6, 16, 40, 0.9); border: 4px solid rgba(255,255,255,0.9); box-shadow: inset 0 4px 14px rgba(0, 240, 255, 0.35), inset 0 -4px 10px rgba(0,0,0,0.6), 0 12px 32px rgba(0,0,0,0.5), 0 0 28px rgba(0, 220, 255, 0.45); }
.thinking-bar-capsule-liquid .capsule-metal-cap { width: 28px; height: 100%; display: grid; place-items: center; background: linear-gradient(180deg, #E2E8F0 0%, #64748B 50%, #1E293B 100%); z-index: 4; }
.thinking-bar-capsule-liquid .cap-left { border-radius: 9999px 0 0 9999px; border-right: 2px solid rgba(0,240,255,0.5); }
.thinking-bar-capsule-liquid .cap-right { border-radius: 0 9999px 9999px 0; border-left: 2px solid rgba(0,240,255,0.5); }
.thinking-bar-capsule-liquid .cap-rivet { width: 8px; height: 8px; border-radius: 50%; background: #00FF9D; box-shadow: 0 0 8px #00FF9D; }
.thinking-bar-capsule-liquid .capsule-glass-chamber { position: relative; flex: 1; height: 100%; overflow: hidden; background: radial-gradient(ellipse at center, #0B224C 0%, #030B1C 100%); }
.thinking-bar-capsule-liquid .capsule-liquid-fill { position: absolute; top: 0; left: 0; bottom: 0; width: 100%; border-radius: 9999px; background: linear-gradient(90deg, #FF007F 0%, #7000FF 30%, #00F0FF 70%, #00FF9D 100%); background-size: 1540px 100%; background-position: left center; z-index: 1; animation: quiz-timer-drain var(--timer-duration) linear var(--timer-start) both; overflow: hidden; box-shadow: 0 0 20px rgba(0,240,255,0.8), inset 0 0 10px rgba(255,255,255,0.6); }
.thinking-bar-capsule-liquid .liquid-wave-front { position: absolute; top: 0; bottom: 0; right: 0; width: 36px; background: linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.8) 100%); pointer-events: none; }
.thinking-bar-capsule-liquid .flask-volume-ticks { position: absolute; inset: 0; display: flex; justify-content: space-between; padding: 0 24px; align-items: center; pointer-events: none; z-index: 3; }
.thinking-bar-capsule-liquid .flask-volume-ticks span { width: 2px; height: 16px; background: rgba(255,255,255,0.4); box-shadow: 0 0 4px rgba(255,255,255,0.6); }
.thinking-bar-capsule-liquid .liquid-bubbles { position: absolute; inset: 0; pointer-events: none; z-index: 3; }
.thinking-bar-capsule-liquid .bub { position: absolute; border-radius: 50%; background: rgba(255,255,255,0.85); box-shadow: 0 0 10px rgba(255,255,255,1); animation: liquidBubbleRise 2.2s infinite ease-in-out; }
.thinking-bar-capsule-liquid .bub-1 { width: 10px; height: 10px; left: 15%; bottom: 6px; animation-delay: 0s; }
.thinking-bar-capsule-liquid .bub-2 { width: 14px; height: 14px; left: 38%; bottom: 8px; animation-delay: 0.5s; }
.thinking-bar-capsule-liquid .bub-3 { width: 8px; height: 8px; left: 62%; bottom: 4px; animation-delay: 1.0s; }
.thinking-bar-capsule-liquid .bub-4 { width: 12px; height: 12px; left: 82%; bottom: 10px; animation-delay: 0.3s; }
.thinking-bar-capsule-liquid .bub-5 { width: 16px; height: 16px; left: 94%; bottom: 6px; animation-delay: 1.6s; }
.thinking-bar-capsule-liquid .capsule-glass-glare { position: absolute; top: 2px; left: 8px; right: 8px; height: 32%; border-radius: 9999px; background: linear-gradient(180deg, rgba(255,255,255,0.7) 0%, rgba(255,255,255,0.15) 65%, transparent 100%); pointer-events: none; z-index: 4; }
.thinking-bar-capsule-liquid .capsule-bottom-reflection { position: absolute; bottom: 2px; left: 16px; right: 16px; height: 20%; border-radius: 9999px; background: linear-gradient(0deg, rgba(255,255,255,0.3) 0%, transparent 100%); pointer-events: none; z-index: 4; }
.thinking-bar-capsule-liquid .capsule-timer-marker { position: absolute; top: 50%; left: 100%; display: grid; place-items: center; width: 180px; height: 180px; transform: translate(-50%,-50%); animation: quiz-timer-marker-slide var(--timer-duration) linear var(--timer-start) both; z-index: 7; }
.thinking-bar-capsule-liquid .capsule-orb-svg { position: absolute; inset: 0; width: 100%; height: 100%; overflow: visible; pointer-events: none; }
.thinking-bar-capsule-liquid .mana-sparkles-fx { position: absolute; inset: 0; pointer-events: none; z-index: 6; }
.thinking-bar-capsule-liquid .mana-sparkles-fx i { position: absolute; font-style: normal; font-size: 16px; color: #FFF; text-shadow: 0 0 10px #00F0FF; }
.thinking-bar-capsule-liquid .mana-sparkles-fx i:nth-child(1) { top: 6px; right: 24px; }
.thinking-bar-capsule-liquid .mana-sparkles-fx i:nth-child(2) { bottom: 12px; left: 20px; font-size: 18px; color: #00FF9D; }
.thinking-bar-capsule-liquid .mana-sparkles-fx i:nth-child(3) { top: 22px; left: 18px; font-size: 14px; }
.thinking-bar-capsule-liquid .marker-val { text-shadow: 0 0 14px #00F0FF, 0 0 28px #00D5FF, 0 3px 6px rgba(0,0,0,0.95); }
@keyframes liquidBubbleRise { 0% { transform: translateY(0) scale(0.8); opacity: 0; } 50% { opacity: 0.9; } 100% { transform: translateY(-42px) scale(1.25); opacity: 0; } }
`;
  },
};
