import { calculateThinkingBarTiming, type ThinkingBarRenderInput, type ThinkingBarVariant } from "../types.js";

const REACTOR_CORE_SVG = `<svg class="laser-reactor-svg" viewBox="0 0 180 180" aria-hidden="true" data-layout-ignore><defs><linearGradient id="cyberHexGrad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#00F0FF" /><stop offset="45%" stop-color="#8A2BE2" /><stop offset="100%" stop-color="#FF007F" /></linearGradient><linearGradient id="armorRimGrad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#E2E8F0" /><stop offset="50%" stop-color="#64748B" /><stop offset="100%" stop-color="#1E293B" /></linearGradient><radialGradient id="quantumCoreAperture" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="#020713" /><stop offset="70%" stop-color="#05122C" /><stop offset="100%" stop-color="#092354" /></radialGradient><radialGradient id="reactorShieldAura" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="rgba(0,240,255,0.45)" /><stop offset="65%" stop-color="rgba(138,43,226,0.25)" /><stop offset="100%" stop-color="rgba(0,0,0,0)" /></radialGradient></defs><circle cx="90" cy="90" r="84" fill="url(#reactorShieldAura)" /><polygon points="90,14 156,52 156,128 90,166 24,128 24,52" fill="#060E20" stroke="url(#cyberHexGrad)" stroke-width="7" stroke-linejoin="round" filter="drop-shadow(0 0 16px rgba(0,240,255,0.9))" /><polygon points="90,24 146,56 146,124 90,156 34,124 34,56" fill="none" stroke="url(#armorRimGrad)" stroke-width="2.5" opacity="0.75" /><g class="gyro-ring-outer" transform-origin="90 90"><circle cx="90" cy="90" r="58" fill="none" stroke="#00F0FF" stroke-width="2" stroke-dasharray="14 8 4 8" opacity="0.9" /><circle cx="90" cy="90" r="62" fill="none" stroke="#FF007F" stroke-width="1.5" stroke-dasharray="6 12" opacity="0.75" /></g><g class="gyro-ring-inner" transform-origin="90 90"><circle cx="90" cy="90" r="50" fill="none" stroke="#00F0FF" stroke-width="2" stroke-dasharray="8 8" opacity="0.85" /></g><circle cx="90" cy="90" r="46" fill="url(#quantumCoreAperture)" stroke="#00F0FF" stroke-width="4" /><circle cx="90" cy="90" r="48" fill="none" stroke="#FFE600" stroke-width="1.5" stroke-dasharray="12 36" /><polygon points="90,36 94,44 86,44" fill="#FFE600" /><polygon points="90,144 94,136 86,136" fill="#FFE600" /><polygon points="36,90 44,94 44,86" fill="#FFE600" /><polygon points="144,90 136,94 136,86" fill="#FFE600" /><path d="M28 42 L22 36 M152 42 L158 36 M28 138 L22 144 M152 138 L158 144" stroke="#00F0FF" stroke-width="3" stroke-linecap="round" filter="drop-shadow(0 0 6px #00F0FF)" /></svg>`;

export const energyLaserVariant: ThinkingBarVariant = {
  id: "energy_laser",
  displayName: "Cyber Plasma Bar",
  description: "Sci-Fi high-voltage plasma laser beam with pulsing electric arcs and intense charge decay.",
  renderHtml(input: ThinkingBarRenderInput): string {
    const timing = calculateThinkingBarTiming(input);
    return `<div class="thinking-bar thinking-bar-energy-laser" ${timing.styleAttr}><div class="laser-track" aria-label="Quiz laser timer" data-layout-allow-overflow><div class="laser-chassis-endcap endcap-left" data-layout-ignore aria-hidden="true"><span class="endcap-led led-1"></span><span class="endcap-led led-2"></span></div><div class="laser-chamber-tunnel"><div class="laser-grid-bg" data-layout-ignore aria-hidden="true"></div><div class="laser-beam-progress"><div class="laser-plasma-core"></div><div class="laser-plasma-arcs"></div><div class="laser-focal-flare"></div></div><div class="laser-containment-rings" data-layout-ignore aria-hidden="true"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div></div><div class="laser-chassis-endcap endcap-right" data-layout-ignore aria-hidden="true"><span class="endcap-led led-1"></span><span class="endcap-led led-2"></span></div><span class="laser-reactor-marker" data-layout-allow-occlusion data-layout-allow-overlap>${REACTOR_CORE_SVG}<b class="marker-val val-query" data-layout-allow-overlap>?</b><b class="marker-val val-5" data-layout-allow-overlap>5</b><b class="marker-val val-4" data-layout-allow-overlap>4</b><b class="marker-val val-3" data-layout-allow-overlap>3</b><b class="marker-val val-2" data-layout-allow-overlap>2</b><b class="marker-val val-1" data-layout-allow-overlap>1</b></span></div></div>`;
  },
  renderCss(): string {
    return `
.thinking-bar-energy-laser .laser-track { position: relative; z-index: 0; width: 100%; height: 62px; overflow: visible; display: flex; align-items: center; border-radius: 16px; background: linear-gradient(180deg, #0A1428 0%, #030814 100%); border: 3px solid #00F0FF; box-shadow: 0 0 24px rgba(0, 240, 255, 0.45), inset 0 0 16px rgba(0, 240, 255, 0.25), 0 16px 36px rgba(0,0,0,0.65); }
.thinking-bar-energy-laser .laser-chassis-endcap { width: 32px; height: 100%; display: flex; flex-direction: column; justify-content: space-around; align-items: center; padding: 10px 0; background: linear-gradient(180deg, #1E293B 0%, #0F172A 100%); border: 2px solid rgba(0,240,255,0.6); z-index: 4; }
.thinking-bar-energy-laser .endcap-left { border-radius: 12px 0 0 12px; border-right: none; }
.thinking-bar-energy-laser .endcap-right { border-radius: 0 12px 12px 0; border-left: none; }
.thinking-bar-energy-laser .endcap-led { width: 6px; height: 6px; border-radius: 50%; background: #00F0FF; box-shadow: 0 0 8px #00F0FF; animation: ledBlink 1.2s infinite alternate; }
.thinking-bar-energy-laser .endcap-led.led-2 { background: #FF007F; box-shadow: 0 0 8px #FF007F; animation-delay: 0.6s; }
.thinking-bar-energy-laser .laser-chamber-tunnel { position: relative; flex: 1; height: 100%; overflow: hidden; background: radial-gradient(ellipse at center, #0B1E44 0%, #020714 100%); }
.thinking-bar-energy-laser .laser-grid-bg { position: absolute; inset: 0; background-image: repeating-linear-gradient(90deg, rgba(0,240,255,0.08) 0px, rgba(0,240,255,0.08) 20px, transparent 20px, transparent 40px), linear-gradient(0deg, rgba(0,240,255,0.05) 1px, transparent 1px); background-size: 40px 100%, 100% 8px; pointer-events: none; }
.thinking-bar-energy-laser .laser-beam-progress { position: absolute; top: 6px; left: 0; bottom: 6px; width: 100%; border-radius: 8px; background: linear-gradient(90deg, #FF0055 0%, #9D00FF 30%, #00F0FF 75%, #FFFFFF 100%); background-size: 1540px 100%; background-position: left center; z-index: 1; animation: quiz-timer-drain var(--timer-duration) linear var(--timer-start) both; overflow: visible; box-shadow: 0 0 20px rgba(0,240,255,0.7), inset 0 0 10px rgba(255,255,255,0.9); }
.thinking-bar-energy-laser .laser-plasma-core { position: absolute; top: 50%; left: 0; right: 0; height: 8px; transform: translateY(-50%); background: #FFFFFF; box-shadow: 0 0 12px #FFFFFF, 0 0 28px #00F0FF, 0 0 44px #9D00FF; opacity: 0.95; }
.thinking-bar-energy-laser .laser-plasma-arcs { position: absolute; inset: 0; background: linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.8) 50%, transparent 100%); animation: laserPulseScan 1.1s infinite linear; }
.thinking-bar-energy-laser .laser-focal-flare { position: absolute; top: 50%; right: -8px; width: 20px; height: 38px; transform: translateY(-50%); border-radius: 50%; background: #FFFFFF; box-shadow: 0 0 18px 4px #FFFFFF, 0 0 32px 10px #00F0FF, 0 0 48px 18px #FF007F; pointer-events: none; z-index: 2; animation: laserFlarePulse 0.4s infinite alternate; }
.thinking-bar-energy-laser .laser-containment-rings { position: absolute; inset: 0; display: flex; justify-content: space-between; padding: 0 18px; align-items: center; pointer-events: none; z-index: 3; }
.thinking-bar-energy-laser .laser-containment-rings span { width: 3px; height: 26px; background: rgba(0,240,255,0.5); box-shadow: 0 0 8px #00F0FF; border-radius: 2px; }
.thinking-bar-energy-laser .laser-reactor-marker { position: absolute; top: 50%; left: 100%; display: grid; place-items: center; width: 180px; height: 180px; transform: translate(-50%,-50%); animation: quiz-timer-marker-slide var(--timer-duration) linear var(--timer-start) both; z-index: 7; }
.thinking-bar-energy-laser .laser-reactor-svg { position: absolute; inset: 0; width: 100%; height: 100%; overflow: visible; pointer-events: none; }
.thinking-bar-energy-laser .gyro-ring-outer { animation: gyroRingSpin 14s linear infinite; }
.thinking-bar-energy-laser .gyro-ring-inner { animation: gyroRingSpinReverse 9s linear infinite; }
.thinking-bar-energy-laser .marker-val { text-shadow: 0 0 14px #00F0FF, 0 0 28px #0080FF, 0 3px 6px rgba(0,0,0,0.95); }
@keyframes laserPulseScan { 0% { transform: translateX(-100%); } 100% { transform: translateX(200%); } }
@keyframes laserFlarePulse { 0% { opacity: 0.8; transform: translateY(-50%) scale(0.9); } 100% { opacity: 1; transform: translateY(-50%) scale(1.15); } }
@keyframes gyroRingSpin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
@keyframes gyroRingSpinReverse { from { transform: rotate(0deg); } to { transform: rotate(-360deg); } }
@keyframes ledBlink { 0% { opacity: 0.4; transform: scale(0.85); } 100% { opacity: 1; transform: scale(1.2); } }
`;
  },
};
