import type { VisualProxyRule } from "./sanitizerTypes.js";

export const EXTENDED_VISUAL_RULES: VisualProxyRule[] = [
  {
    id: "lion_cub_sensitive",
    pattern: /\b(?:lion\s+cubs?|baby\s+lions?|lion\s+bab(?:y|ies))\b/i,
    fullProxy: "A majestic young golden lion resting beneath sweeping acacia trees on the African plains.",
    inlineProxy: "a majestic young golden lion",
    category: "LION_CUB",
    forbiddenKeywords: ["lion cub", "baby lion", "lion baby"],
  },
  {
    id: "minecraft_creeper",
    pattern: /\b(?:minecraft\s+)?creeper\b/i,
    fullProxy: "A pixelated green explosive block creature with a frowning face in a blocky voxel landscape.",
    inlineProxy: "a pixelated green block creature",
    category: "GAME_IP",
    forbiddenKeywords: ["Creeper", "Minecraft"],
  },
  {
    id: "minecraft_steve",
    pattern: /\b(?:minecraft\s+steve|steve\s+from\s+minecraft)\b/i,
    fullProxy: "A blocky voxel adventurer in a teal shirt and blue trousers carrying a stone pickaxe.",
    inlineProxy: "a blocky voxel adventurer",
    category: "GAME_IP",
    forbiddenKeywords: ["Steve", "Minecraft"],
  },
  {
    id: "minecraft_world",
    pattern: /\bminecraft\b/i,
    fullProxy: "A vibrant blocky voxel sandbox landscape with cubic trees, pixelated terrain, and geometric blocks.",
    inlineProxy: "a blocky voxel landscape",
    category: "GAME_IP",
    forbiddenKeywords: ["Minecraft", "Mojang"],
  },
  {
    id: "spiderman",
    pattern: /\bspider[- ]?man\b/i,
    fullProxy: "A heroic costumed acrobat in a red and blue web-patterned suit swinging dynamically between city skyscrapers.",
    inlineProxy: "a heroic web-slinging costumed acrobat",
    category: "MARVEL_SUPERHERO",
    forbiddenKeywords: ["Spider-Man", "Spiderman", "Peter Parker"],
  },
  {
    id: "batman",
    pattern: /\bbatman\b/i,
    fullProxy: "A dark cloaked vigilante detective in a bat-eared cowl and armored suit perched on a gothic city gargoyle.",
    inlineProxy: "a dark cloaked vigilante detective",
    category: "DC_SUPERHERO",
    forbiddenKeywords: ["Batman", "Bruce Wayne", "Gotham"],
  },
  {
    id: "superman",
    pattern: /\bsuperman\b/i,
    fullProxy: "A noble flying superhero in a blue suit with red cape and stylized chest emblem soaring above a gleaming metropolis.",
    inlineProxy: "a noble cape-wearing flying superhero",
    category: "DC_SUPERHERO",
    forbiddenKeywords: ["Superman", "Clark Kent"],
  },
  {
    id: "iron_man",
    pattern: /\biron[- ]?man\b/i,
    fullProxy: "A high-tech superhero in gleaming crimson and gold robotic flight armor with glowing chest arc reactor.",
    inlineProxy: "an armored crimson and gold robotic hero",
    category: "MARVEL_SUPERHERO",
    forbiddenKeywords: ["Iron Man", "Tony Stark"],
  },
  {
    id: "captain_america",
    pattern: /\bcaptain\s+america\b/i,
    fullProxy: "A patriotic tactical hero in star-spangled armor carrying a polished circular star shield.",
    inlineProxy: "a star-spangled shield-bearing hero",
    category: "MARVEL_SUPERHERO",
    forbiddenKeywords: ["Captain America", "Steve Rogers"],
  },
  {
    id: "hulk",
    pattern: /\b(?:the\s+)?incredible\s+hulk\b|\bhulk\b/i,
    fullProxy: "A colossal muscular green giant with formidable strength and torn purple trousers.",
    inlineProxy: "a colossal muscular green giant",
    category: "MARVEL_SUPERHERO",
    forbiddenKeywords: ["Hulk", "Bruce Banner"],
  },
  {
    id: "wonder_woman",
    pattern: /\bwonder\s+woman\b/i,
    fullProxy: "A courageous amazon warrior princess in golden tiara and armor holding a glowing lasso of truth.",
    inlineProxy: "an amazon warrior princess in golden armor",
    category: "DC_SUPERHERO",
    forbiddenKeywords: ["Wonder Woman", "Diana Prince"],
  },
  {
    id: "elsa_frozen",
    pattern: /\b(?:queen\s+)?elsa\b/i,
    fullProxy: "An elegant ice sorceress queen in a shimmering crystalline azure frost gown casting swirling snowflakes.",
    inlineProxy: "an elegant ice sorceress queen",
    category: "DISNEY_CORE",
    forbiddenKeywords: ["Elsa", "Frozen"],
  },
  {
    id: "olaf_frozen",
    pattern: /\bolaf\b/i,
    fullProxy: "A cheerful whimsical snowman with twig arms, a carrot nose, and buck-toothed smile on snowy slopes.",
    inlineProxy: "a cheerful whimsical snowman",
    category: "DISNEY_CORE",
    forbiddenKeywords: ["Olaf", "Frozen"],
  },
  {
    id: "darth_vader",
    pattern: /\bdarth\s+vader\b/i,
    fullProxy: "An imposing dark space commander in polished black helmet and sweeping obsidian cape.",
    inlineProxy: "an imposing dark space commander",
    category: "CINEMA_IP",
    forbiddenKeywords: ["Darth Vader", "Star Wars"],
  },
  {
    id: "yoda",
    pattern: /\b(?:master\s+)?yoda\b/i,
    fullProxy: "A wise diminutive green alien master with large pointed ears in rustic robes holding a gnarled walking staff.",
    inlineProxy: "a wise diminutive green alien master",
    category: "CINEMA_IP",
    forbiddenKeywords: ["Yoda", "Star Wars"],
  },
];
