import React from "react";
import { CircleNotch, Image, Sparkle, UploadSimple, WarningCircle } from "@phosphor-icons/react";
import type { QuestionImageStatus } from "../../types/questionImages.types";

export interface QuestionImageStatusBadgeProps {
  status: QuestionImageStatus;
}

export function QuestionImageStatusBadge({ status }: QuestionImageStatusBadgeProps): React.JSX.Element {
  switch (status) {
    case "user_uploaded":
      return (
        <span className="question-image-badge badge-status-user" role="status" title="Custom user-uploaded image">
          <UploadSimple size={13} weight="bold" />
          <span>Manual Upload</span>
        </span>
      );
    case "ai_generated":
      return (
        <span className="question-image-badge badge-status-ai" role="status" title="Generated by AI image provider">
          <Sparkle size={13} weight="fill" />
          <span>AI Generated</span>
        </span>
      );
    case "generating":
      return (
        <span className="question-image-badge badge-status-generating" role="status" title="Image generation in progress">
          <CircleNotch size={13} className="spin" weight="bold" />
          <span>Generating...</span>
        </span>
      );
    case "fallback":
      return (
        <span className="question-image-badge badge-status-fallback" role="status" title="Fallback image used">
          <WarningCircle size={13} weight="bold" />
          <span>Fallback</span>
        </span>
      );
    case "missing":
    default:
      return (
        <span className="question-image-badge badge-status-missing" role="status" title="No image assigned yet">
          <Image size={13} weight="bold" />
          <span>Missing</span>
        </span>
      );
  }
}
