import type {
  ArchetypePromptStrategy,
  BuildBatchPromptOptions,
  BuildReverseBatchPromptOptions,
} from "./promptStrategy.types.js";
import {
  COMMON_BATCH_CONTENT_POLICY_LINES,
  COMMON_REVERSE_CONTENT_POLICY_LINES,
  FRANCHISE_ANCHOR_MANDATE_LINES,
  VISUAL_ANCHOR_MANDATE_LINES,
  formatExistingSamplesBlock,
  formatTargetEntitiesBlock,
} from "./promptCommonBlocks.js";

const GOLDEN_DEEP_TRIVIA_PARADIGMS: string[] = [
  "=== GOLDEN DEEP TRIVIA PARADIGMS (PUNCHY & DIVERSE HOOKS) ===",
  "CRITICAL: Strictly 60 to 80 characters (never exceed 80 chars). NEVER repeat \"Which [noun] [verb]...\" monotonically. Rotate across these 5 ultra-concise styles:",
  '1. Feat / Signature Action: "In Dragon Ball Z, whose signature energy wave is the Kamehameha?" -> Choices: [A: Son Goku (Correct), B: Vegeta, C: Piccolo]',
  '2. Iconic Relic / Hallmarks: "In One Piece, what straw accessory was given to Luffy by Shanks?" -> Choices: [A: Straw Hat (Correct), B: Red Cloak, C: Gold Compass]',
  '3. Universal Mascot / Partner: "In Pokemon, which electric mouse is Ash Ketchum\'s loyal partner?" -> Choices: [A: Pikachu (Correct), B: Raichu, C: Eevee]',
  '4. Signature Jutsu / Technique: "In Naruto, which swirling blue sphere technique did Minato invent?" -> Choices: [A: Rasengan (Correct), B: Chidori, C: Amaterasu]',
  '5. Detective Gadget / Identity: "In Detective Conan, what gadget lets Conan mimic Kogoro\'s voice?" -> Choices: [A: Voice-Changing Bowtie (Correct), B: Power Shoes, C: Tracking Glasses]',
];

const SPECIALIZED_DEEP_TRIVIA_DIRECTIVE: string[] = [
  "=== SPECIALIZED DEEP TRIVIA DIRECTIVE ===",
  "CRITICAL RULES FOR DEEP TRIVIA (HIGH ENGAGEMENT & MOBILE BREVITY):",
  "1. CONCISE BREVITY MANDATE: Question length strictly 60 to 80 characters (never exceed 80 chars) to prevent font shrinkage or text clipping on mobile screens.",
  '2. ANTI-MONOTONY & NO FILLER NOUNS: STRICTLY FORBIDDEN to monotonically open questions with "Which [category noun] [verb]..." (e.g. "Which villain...", "Which sorcerer...", "Which animal..."). Drop redundant category labels because the choices already display the candidates!',
  "3. HOOK VARIETY ROTATION: Rotate continuously across these 5 punchy phrasing styles:",
  '   - Feat / Signature Action: "In Dragon Ball Z, whose signature energy wave is the Kamehameha?"',
  '   - Iconic Relic / Hallmarks: "In One Piece, what straw accessory was given to Luffy by Shanks?"',
  '   - Universal Mascot / Partner: "In Pokemon, which electric mouse is Ash Ketchum\'s loyal partner?"',
  '   - Signature Jutsu / Technique: "In Naruto, which swirling blue sphere technique did Minato invent?"',
  '   - Detective Gadget / Identity: "In Detective Conan, what gadget lets Conan mimic Kogoro\'s voice?"',
  "4. ANCHORING: Root each question deeply into the Target Entity's most surprising lore, verified science, or iconic breakthrough.",
  "5. FRANCHISE ANCHORING: If the target entity belongs to anime, manga, gaming, comics, movies, or fictional lore, ALWAYS explicitly include the parent franchise name using short umbrella titles (e.g. 'In Spider-Man', 'In Lord of the Rings'). NEVER include lengthy movie subtitles or arc tags.",
];

const MIND_BLOWING_EDUTAINMENT_MANDATE: string[] = [
  "=== MIND-BLOWING EDUTAINMENT TRIVIA MANDATE (NO DRY DEFINITIONS / NO CLOSE SIBLINGS) ===",
  "CRITICAL RULES TO AVOID ACADEMIC BOREDOM & PEDANTIC CONFUSION:",
  "1. FORBIDDEN - DRY JOB-DESCRIPTIONS & VOCABULARY DRILLS:",
  "   - NEVER formulate dry job-description questions (e.g. NEVER ask 'Using insulated tools, who wires circuit breaker panels?' or 'Who brushes dirt off pottery shards?').",
  "   - NEVER create questions that read like a grade-school textbook vocabulary test.",
  "2. FORBIDDEN - PEDANTIC SIBLING DISTRACTOR TRAPS:",
  "   - NEVER pit ultra-close sibling titles against each other where viewers argue over overlapping job boundaries (e.g. NEVER Electrician vs Electrical Engineer, Chemist vs Chemical Engineer).",
  "   - NEVER pit near-identical marine mammals or subspecies together (e.g. NEVER Leopard Seal vs Walrus vs Elephant Seal on obscure predatory mechanics).",
  "   - Choices A, B, and C MUST represent distinct, universally recognizable entities or icons with zero ambiguity.",
  "3. FORBIDDEN - GORY OR OBSCURE BEHAVIORAL MECHANICS:",
  "   - NEVER ask about grotesque or gory predatory mechanics (e.g. thrashing animals to peel skin).",
  "4. STRICT MOBILE QUESTION BREVITY (STRICTLY 60–80 CHARACTERS):",
  "   - On 9:16 vertical Shorts/Reels, the question box fits at most 2 lines. Keep question strictly 60 to 80 characters (never exceed 80 chars).",
  "   - NEVER pack paragraph-length backstories into the question box. Keep the hook punchy and readable in under 2 seconds.",
  "   - Reserve rich historical, scientific, or narrative context strictly for the 'explanation' and 'fun_fact' fields!",
];

export const deepTriviaPromptStrategy: ArchetypePromptStrategy = {
  archetypeId: "deep_trivia",

  buildBatchPrompt(options: BuildBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";
    const subtopicTitle = options.subtopicTitle || options.subtopicId.replaceAll("_", " ");

    return [
      `You are a world-class Quiz & Trivia Designer for short-form video platforms (YouTube Shorts / TikTok / Reels).`,
      `Your mission is to create exactly ${options.count} unique, high-retention, engaging trivia questions.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Archetype: "deep_trivia"`,
      `- Domain: "${options.domainId}"`,
      `- Subtopic: "${options.subtopicId}" ("${subtopicTitle}")`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Language: "${lang}"`,
      `- Format: "multiple_choice"`,
      `- Choice Count: 3`,
      `- Thinking Duration: 6 seconds`,
      ``,
      ...GOLDEN_DEEP_TRIVIA_PARADIGMS,
      ``,
      ...MIND_BLOWING_EDUTAINMENT_MANDATE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== MOBILE VIDEO SHORTS LENGTH & PACING RULES (STRICT) ===`,
      `1. QUESTION LENGTH: Strictly 60 to 80 characters (never exceed 80 chars). Must fit in 2 lines on mobile vertical screens.`,
      `2. PUNCHY HOOK ONLY: Keep question text readable under 2 seconds. Move all background narrative to explanation.`,
      ``,
      ...COMMON_BATCH_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array containing ${options.count} question objects. NO markdown fences, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "archetype_id": "deep_trivia",`,
      `    "domain_id": "${options.domainId}",`,
      `    "subtopic_id": "${options.subtopicId}",`,
      `    "question": "In Dragon Ball Z, whose signature beam is the Kamehameha?",`,
      `    "format": "multiple_choice",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Son Goku", "is_correct": true },`,
      `      { "id": "B", "text": "Vegeta", "is_correct": false },`,
      `      { "id": "C", "text": "Piccolo", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "Master Roshi originally invented the Kamehameha, which Goku learned instantly.",`,
      `    "fun_fact": "Toriyama's wife suggested the name Kamehameha after the Hawaiian king.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Detailed cinematic visual prompt in English: explicitly name entity and franchise, signature traits, and iconic environment",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "age_band": "${ageBand}",`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 6,`,
      `    "tags": ["${options.subtopicId}", "deep_trivia"]`,
      `  }`,
      `]`,
    ].join("\n");
  },

  buildReversePrompt(options: BuildReverseBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";

    return [
      `You are an elite Quiz Architect creating high-retention video trivia for YouTube Shorts & TikTok.`,
      `Your task is to generate exactly ${options.targets.length} questions, strictly mapping 1-to-1 to each target entity provided below.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Gameplay Archetype: "deep_trivia"`,
      `- Format: "multiple_choice"`,
      `- Choice Count: 3`,
      `- Default Thinking Seconds: 6`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Target Language: "${lang}"`,
      ``,
      `=== TARGET ENTITIES (EXACTLY 1 QUESTION PER ENTITY) ===`,
      formatTargetEntitiesBlock(options.targets),
      ``,
      ...SPECIALIZED_DEEP_TRIVIA_DIRECTIVE,
      ``,
      ...MIND_BLOWING_EDUTAINMENT_MANDATE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== REVERSE MATRIX GENERATION CONTRACT (STRICT) ===`,
      `1. 1-to-1 MAPPING: Generate exactly ${options.targets.length} questions, in the exact order of the Target Entities.`,
      `2. ENTITY ANCHOR: For each question, set "entity_id" to the corresponding Entity ID.`,
      `3. TRUTH & ACCURACY: Base the question directly on verified traits or rivals. Do NOT hallucinate facts.`,
      `4. DISTRACTORS: Draw plausible wrong choices from the provided Distractor Pool or Versus Rivals. Ensure choices represent distinct, non-confusing categories.`,
      `5. CONCISE HOOK: Strictly 60 to 80 characters (never exceed 80 chars) to fit 2 lines on mobile screens.`,
      ``,
      ...COMMON_REVERSE_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY JSON OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array of ${options.targets.length} question objects. NO markdown, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "entity_id": "ENT-...",`,
      `    "archetype_id": "deep_trivia",`,
      `    "domain_id": "<target domain>",`,
      `    "subtopic_id": "<target subtopic>",`,
      `    "question": "Punchy question text?",`,
      `    "format": "multiple_choice",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Correct Entity Name", "is_correct": true },`,
      `      { "id": "B", "text": "Distractor 1", "is_correct": false },`,
      `      { "id": "C", "text": "Distractor 2", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "Clear explanation of the answer.",`,
      `    "fun_fact": "Surprising related fact.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Detailed cinematic visual prompt in English based on Visual Anchor and entity lore",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 6,`,
      `    "tags": ["<subtopic_id>", "deep_trivia"]`,
      `  }`,
      `]`,
    ].join("\n");
  },
};
