import type {
  ArchetypePromptStrategy,
  BuildBatchPromptOptions,
  BuildReverseBatchPromptOptions,
} from "./promptStrategy.types.js";
import {
  COMMON_BATCH_CONTENT_POLICY_LINES,
  COMMON_REVERSE_CONTENT_POLICY_LINES,
  FRANCHISE_ANCHOR_MANDATE_LINES,
  VISUAL_ANCHOR_MANDATE_LINES,
  formatExistingSamplesBlock,
  formatTargetEntitiesBlock,
} from "./promptCommonBlocks.js";
import { GRAPHIC_IDENTITY_MANDATE_LINES } from "../archetypePromptGuidelines.js";

const GOLDEN_MYSTERY_REVEAL_PARADIGMS: string[] = [
  "=== GOLDEN MYSTERY REVEAL PARADIGMS (SILHOUETTE SUSPENSE EXAMPLES) ===",
  "Study these 4 mystery reveal framing styles (SINGLE REVEAL ANSWER ONLY - NO DISTRACTORS):",
  '1. Stat riddle: "Sees 16 sunrises every day — what orbiting lab is this?" -> [A: International Space Station (Correct)]',
  '2. Scanner teaser: "Behind the scan: Name the rover vaporizing Martian rocks!" -> [A: Curiosity Rover (Correct)]',
  '3. Deep space milestone: "What robotic explorer carried Earth\'s Golden Record?" -> [A: Voyager 1 (Correct)]',
  '4. Silhouette outline: "Can you identify this lunar buggy with wire mesh wheels?" -> [A: Apollo Lunar Rover (Correct)]',
];

const SPECIALIZED_MYSTERY_REVEAL_DIRECTIVE: string[] = [
  "=== SPECIALIZED MYSTERY REVEAL DIRECTIVE ===",
  "CRITICAL RULES FOR SILHOUETTE & SCANNER REVEAL:",
  "1. SUSPENSE & SILHOUETTE FRAMING: DO NOT use repetitive 'Which [adjective] [noun] [verb]?' templates. Frame each question around a hidden contour, outline, or dramatic reveal.",
  "2. REVEAL HOOK ROTATION: Rotate across these 5 phrasing patterns:",
  '   - Silhouette guess: "Can you guess this [craft / creature] from its silhouette?"',
  '   - Scanner teaser: "Behind the scan beam: Name the [machine / explorer] that [action]!"',
  '   - Stat riddle: "[Surprising stat/milestone] — what [vehicle / subject] is hiding here?"',
  '   - Shadow identification: "Whose outline is concealed in this mystery reveal?"',
  '   - Unmasking challenge: "Unmask the legend: Which [craft / figure] [historic achievement]?"',
  "3. ANCHORING: Base the visual silhouette description in visual_spec on the entity's iconic visual_anchor.",
  "4. SINGLE ANSWER ONLY: Exactly ONE choice (the canonical target answer). NEVER include distractors or wrong options.",
];

export const mysteryRevealPromptStrategy: ArchetypePromptStrategy = {
  archetypeId: "mystery_reveal",

  buildBatchPrompt(options: BuildBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";
    const subtopicTitle = options.subtopicTitle || options.subtopicId.replaceAll("_", " ");

    return [
      `You are a world-class Suspense & Silhouette Puzzle Designer for short-form video platforms (YouTube Shorts / TikTok / Reels).`,
      `Your mission is to create exactly ${options.count} unique Mystery Reveal challenges.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Archetype: "mystery_reveal"`,
      `- Domain: "${options.domainId}"`,
      `- Subtopic: "${options.subtopicId}" ("${subtopicTitle}")`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Language: "${lang}"`,
      `- Format: "image_guess"`,
      `- Choice Count: 1 (Single Canonical Answer Revealed)`,
      `- Thinking Duration: 6 seconds`,
      ``,
      ...GOLDEN_MYSTERY_REVEAL_PARADIGMS,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      ...GRAPHIC_IDENTITY_MANDATE_LINES,
      ``,
      `=== MOBILE VIDEO SHORTS LENGTH & PACING RULES (STRICT) ===`,
      `1. QUESTION LENGTH: Strictly 60 to 80 characters (never exceed 80 chars).`,
      `2. SINGLE ANSWER ONLY: Exactly ONE choice object in the choices array. NO distractors.`,
      ``,
      ...COMMON_BATCH_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array containing ${options.count} question objects. NO markdown fences, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "archetype_id": "mystery_reveal",`,
      `    "domain_id": "${options.domainId}",`,
      `    "subtopic_id": "${options.subtopicId}",`,
      `    "question": "Sees 16 sunrises every day — what orbiting lab is this?",`,
      `    "format": "image_guess",`,
      `    "choices": [`,
      `      { "id": "A", "text": "International Space Station", "is_correct": true }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "The ISS orbits Earth every 90 minutes at roughly 28,000 km/h, witnessing 16 sunrises daily.",`,
      `    "fun_fact": "Astronauts on the ISS experience 16 sunrises and sunsets every 24 hours.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "International Space Station with sprawling solar arrays orbiting above blue Earth silhouette",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "age_band": "${ageBand}",`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 6,`,
      `    "tags": ["${options.subtopicId}", "mystery_reveal"]`,
      `  }`,
      `]`,
    ].join("\n");
  },

  buildReversePrompt(options: BuildReverseBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";

    return [
      `You are an elite Quiz Architect creating high-retention Mystery Reveal challenges for YouTube Shorts & TikTok.`,
      `Your task is to generate exactly ${options.targets.length} questions, strictly mapping 1-to-1 to each target entity provided below.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Gameplay Archetype: "mystery_reveal"`,
      `- Format: "image_guess"`,
      `- Choice Count: 1 (Single Canonical Reveal Answer)`,
      `- Default Thinking Seconds: 6`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Target Language: "${lang}"`,
      ``,
      `=== TARGET ENTITIES (EXACTLY 1 QUESTION PER ENTITY) ===`,
      formatTargetEntitiesBlock(options.targets),
      ``,
      ...SPECIALIZED_MYSTERY_REVEAL_DIRECTIVE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      ...GRAPHIC_IDENTITY_MANDATE_LINES,
      ``,
      `=== REVERSE MATRIX GENERATION CONTRACT (STRICT) ===`,
      `1. 1-to-1 MAPPING: Generate exactly ${options.targets.length} questions, in the exact order of the Target Entities.`,
      `2. ENTITY ANCHOR: For each question, set "entity_id" to the corresponding Entity ID.`,
      `3. TRUTH & ACCURACY: Base the question directly on verified traits or historical achievements.`,
      `4. SINGLE ANSWER: Provide EXACTLY ONE choice (the canonical target entity answer). Do NOT provide distractors or wrong choices.`,
      `5. CONCISE HOOK: Question text must be strictly 60 to 80 characters (never exceed 80 chars).`,
      ``,
      ...COMMON_REVERSE_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY JSON OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array of ${options.targets.length} question objects. NO markdown, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "entity_id": "ENT-...",`,
      `    "archetype_id": "mystery_reveal",`,
      `    "domain_id": "<target domain>",`,
      `    "subtopic_id": "<target subtopic>",`,
      `    "question": "Suspense silhouette question text?",`,
      `    "format": "image_guess",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Canonical Target Name", "is_correct": true }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "Clear explanation of the secret story or background.",`,
      `    "fun_fact": "Surprising related fact.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Detailed cinematic silhouette prompt in English",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 6,`,
      `    "tags": ["<subtopic_id>", "mystery_reveal"]`,
      `  }`,
      `]`,
    ].join("\n");
  },
};
