import type {
  ArchetypePromptStrategy,
  BuildBatchPromptOptions,
  BuildReverseBatchPromptOptions,
} from "./promptStrategy.types.js";
import {
  COMMON_BATCH_CONTENT_POLICY_LINES,
  COMMON_REVERSE_CONTENT_POLICY_LINES,
  FRANCHISE_ANCHOR_MANDATE_LINES,
  formatExistingSamplesBlock,
  formatTargetEntitiesBlock,
} from "./promptCommonBlocks.js";

const GOLDEN_SPEED_BLITZ_PARADIGMS: string[] = [
  "=== GOLDEN SPEED BLITZ PARADIGMS (TOP ENGAGEMENT EXAMPLES) ===",
  "Study these 4 canonical archetypes of high-retention 4-second brainteasers:",
  '1. Geometric Paradox: "A wooden stick has 2 ends. How many ends does half a stick have?" -> Choices: [A: 1 end, B: 2 ends (Correct), C: 0 ends]. Explanation: "When you break a stick in half, the broken piece still has 2 ends!"',
  '2. Shared Attribute Trap: "A family has 6 sons, each with 1 sister. How many kids total?" -> Choices: [A: 7 children (Correct), B: 12 children, C: 6 children]. Explanation: "All 6 brothers share the exact same sister, making 7 children total!"',
  '3. Lateral / Linguistic Trap: "A man walks in the rain with no umbrella, yet no hair gets wet. Why?" -> Choices: [A: He is bald (Correct), B: He ran fast, C: The rain stopped]. Explanation: "The man is completely bald, so he has no hair to get wet!"',
  '4. Overtake Reflex Trap: "You pass the person in second place in a race. What place are you?" -> Choices: [A: 1st place, B: 2nd place (Correct), C: 3rd place]. Explanation: "By overtaking 2nd place, you take their spot in 2nd place!"',
];

const SPECIALIZED_SPEED_BLITZ_DIRECTIVE: string[] = [
  "=== SPECIALIZED SPEED BLITZ COGNITIVE TRAP DIRECTIVE ===",
  "CRITICAL RULE: DO NOT ask dry factual trivia or textbook knowledge about the entity.",
  "Instead, use each Target Entity as the SITUATIONAL CONTEXT for a fast-reflex brainteaser or cognitive trap strictly 60 to 80 characters (never exceed 80 chars):",
  '- Rate / Multiplier Paradox: "If 2 [entities] take 2 min to catch 2 prey, how long do 100 [entities] take to catch 100?" -> 2 min (not 100 min).',
  '- Survival / Permanence Trap: "There are 10 [entities], 3 leave/fall/stop. How many remain?" -> Focus on physical permanence.',
  '- Linguistic & Boundary Trap: "A [entity/vehicle] has an event on a border. Where are survivors buried?" -> Nowhere (survivors aren\'t buried!).',
  '- Interval & Counting Paradox: "A [clock/bell] strikes 6 in 5s. How many seconds to strike 12?" -> Interval count trap.',
  '- Shared Attribute Paradox: "6 [entities] each share 1 partner/sibling. How many total?" -> 7 (not 12!).',
  '- Geometric / Part Paradox: "A [entity/stick/rope] has 2 ends. How many ends does half have?" -> 2 ends!',
  "- Intuitive Misconception Trap: Exploit a common reflex assumption or optical/mental illusion tied to the entity.",
  "Ensure WRONG CHOICES represent the exact instinctive trap that human intuition falls into under a 4-second timer!",
];

export const speedBlitzPromptStrategy: ArchetypePromptStrategy = {
  archetypeId: "speed_blitz",

  buildBatchPrompt(options: BuildBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";
    const subtopicTitle = options.subtopicTitle || options.subtopicId.replaceAll("_", " ");

    return [
      `You are a world-class Quiz & Trivia Designer for short-form video platforms (YouTube Shorts / TikTok / Reels).`,
      `Your mission is to create exactly ${options.count} unique, high-retention fast-reflex brainteasers.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Archetype: "speed_blitz"`,
      `- Domain: "${options.domainId}"`,
      `- Subtopic: "${options.subtopicId}" ("${subtopicTitle}")`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Language: "${lang}"`,
      `- Format: "multiple_choice"`,
      `- Choice Count: 3`,
      `- Thinking Duration: 4 seconds`,
      `- Core Rules:`,
      `  * Rapid reflex riddle, cognitive brainteaser, mental math trap, or lateral wordplay strictly 60 to 80 characters (never exceed 80 chars) for 3-4s fast thinking.`,
      `  * DO NOT ask dry encyclopedic facts, historical dates, or textbook definitions.`,
      `  * Target instinctive cognitive traps where intuitive first-glance logic fails.`,
      `  * Exactly 3 choices (A, B, C): 1 correct counter-intuitive answer and 2 seductive trap choices.`,
      `  * Explanation must clearly reveal the witty 'Aha!' logic in 1-2 punchy sentences.`,
      `  * Visual spec intent is 'none' (pure text focus for maximum speed and reading reflex).`,
      ``,
      ...GOLDEN_SPEED_BLITZ_PARADIGMS,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      `=== MOBILE VIDEO SHORTS LENGTH & PACING RULES (STRICT) ===`,
      `1. QUESTION LENGTH: Strictly 60 to 80 characters (never exceed 80 chars).`,
      `2. Keep the question punchy, readable under 2 seconds.`,
      ``,
      ...COMMON_BATCH_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array containing ${options.count} question objects. NO markdown fences, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "archetype_id": "speed_blitz",`,
      `    "domain_id": "${options.domainId}",`,
      `    "subtopic_id": "${options.subtopicId}",`,
      `    "question": "A wooden stick has 2 ends. How many ends does half a stick have?",`,
      `    "format": "multiple_choice",`,
      `    "choices": [`,
      `      { "id": "A", "text": "2 ends", "is_correct": true },`,
      `      { "id": "B", "text": "1 end", "is_correct": false },`,
      `      { "id": "C", "text": "0 ends", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "When you break a stick in half, the broken piece still has 2 ends!",`,
      `    "fun_fact": "Lateral paradoxes challenge automatic mental assumptions.",`,
      `    "visual_spec": {`,
      `      "intent": "none",`,
      `      "prompt": "",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "age_band": "${ageBand}",`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 4,`,
      `    "tags": ["${options.subtopicId}", "speed_blitz"]`,
      `  }`,
      `]`,
    ].join("\n");
  },

  buildReversePrompt(options: BuildReverseBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";

    return [
      `You are an elite Quiz Architect creating high-retention video trivia for YouTube Shorts & TikTok.`,
      `Your task is to generate exactly ${options.targets.length} questions, strictly mapping 1-to-1 to each target entity provided below.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Gameplay Archetype: "speed_blitz"`,
      `- Format: "multiple_choice"`,
      `- Choice Count: 3`,
      `- Default Thinking Seconds: 4`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Target Language: "${lang}"`,
      ``,
      `=== TARGET ENTITIES (EXACTLY 1 QUESTION PER ENTITY) ===`,
      formatTargetEntitiesBlock(options.targets),
      ``,
      ...SPECIALIZED_SPEED_BLITZ_DIRECTIVE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      `=== REVERSE MATRIX GENERATION CONTRACT (STRICT) ===`,
      `1. 1-to-1 MAPPING: Generate exactly ${options.targets.length} questions, in the exact order of the Target Entities.`,
      `2. ENTITY ANCHOR: For each question, set "entity_id" to the corresponding Entity ID.`,
      `3. TRICK / RIDDLE ANCHOR: Craft a fast-reflex brainteaser or cognitive trap situated around the entity (its traits, behavior, or physical nature).`,
      `4. DISTRACTORS: Draw plausible wrong choices from instinctive human traps under 4 seconds.`,
      `5. CONCISE HOOK: Question text must be strictly 60 to 80 characters (never exceed 80 chars).`,
      ``,
      ...COMMON_REVERSE_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY JSON OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array of ${options.targets.length} question objects. NO markdown, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "entity_id": "ENT-...",`,
      `    "archetype_id": "speed_blitz",`,
      `    "domain_id": "<target domain>",`,
      `    "subtopic_id": "<target subtopic>",`,
      `    "question": "Cognitive trap question text?",`,
      `    "format": "multiple_choice",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Correct Answer", "is_correct": true },`,
      `      { "id": "B", "text": "Trap Choice 1", "is_correct": false },`,
      `      { "id": "C", "text": "Trap Choice 2", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "Witty 'Aha!' logic explanation.",`,
      `    "fun_fact": "Surprising related fact.",`,
      `    "visual_spec": {`,
      `      "intent": "none",`,
      `      "prompt": "",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 4,`,
      `    "tags": ["<subtopic_id>", "speed_blitz"]`,
      `  }`,
      `]`,
    ].join("\n");
  },
};
