import type {
  ArchetypePromptStrategy,
  BuildBatchPromptOptions,
  BuildReverseBatchPromptOptions,
} from "./promptStrategy.types.js";
import {
  COMMON_BATCH_CONTENT_POLICY_LINES,
  COMMON_REVERSE_CONTENT_POLICY_LINES,
  FRANCHISE_ANCHOR_MANDATE_LINES,
  VISUAL_ANCHOR_MANDATE_LINES,
  formatExistingSamplesBlock,
  formatTargetEntitiesBlock,
} from "./promptCommonBlocks.js";

const SPECIALIZED_TRUE_FALSE_DIRECTIVE: string[] = [
  "=== SPECIALIZED TRUE / FALSE ARCHETYPE DIRECTIVE ===",
  'CRITICAL RULE: Standardized exclusively to "True" and "False" format.',
  '1. QUESTION HOOK: Formulate a punchy factual statement or question ending with "... True or False?".',
  '2. CHOICES: Exactly 2 choices with text strictly "True" and "False".',
  "3. TRUTH BALANCE: Enforce a strict ~50/50 distribution across questions (roughly half True, half False as correct choice).",
  "4. ANCHORING: Map [TRUE] claims from the target entity to correct choice \"True\", and [FALSE] claims to correct choice \"False\".",
];

export const verdictPromptStrategy: ArchetypePromptStrategy = {
  archetypeId: ["verdict_true_false", "verdict_fact_myth"],

  buildBatchPrompt(options: BuildBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";
    const subtopicTitle = options.subtopicTitle || options.subtopicId.replaceAll("_", " ");

    return [
      `You are a world-class Quiz & Trivia Designer for short-form video platforms (YouTube Shorts / TikTok / Reels).`,
      `Your mission is to create exactly ${options.count} unique, high-retention True or False questions.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Archetype: "${options.archetypeId}"`,
      `- Domain: "${options.domainId}"`,
      `- Subtopic: "${options.subtopicId}" ("${subtopicTitle}")`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Language: "${lang}"`,
      `- Format: "true_false"`,
      `- Choice Count: 2 ("True" and "False")`,
      `- Thinking Duration: 5 seconds`,
      `- Core Rules:`,
      `  * True or False format. Punchy, single-clause statement or question strictly 60 to 80 characters (never exceed 80 chars).`,
      `  * Format: Direct factual or counter-factual statement ending in 'True or False?'`,
      `  * Exactly 2 choices: 'True' and 'False'.`,
      `  * Truth Balance: Maintain a strict ~50/50 balance between True and False as the correct choice.`,
      `  * Provide a clear explanation along with a scientific/real-world fun fact.`,
      ``,
      ...SPECIALIZED_TRUE_FALSE_DIRECTIVE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== MOBILE VIDEO SHORTS LENGTH & PACING RULES (STRICT) ===`,
      `1. QUESTION LENGTH: Strictly 60 to 80 characters (never exceed 80 chars).`,
      `2. Keep the statement punchy and readable under 2 seconds.`,
      ``,
      ...COMMON_BATCH_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array containing ${options.count} question objects. NO markdown fences, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "archetype_id": "${options.archetypeId}",`,
      `    "domain_id": "${options.domainId}",`,
      `    "subtopic_id": "${options.subtopicId}",`,
      `    "question": "Blue whales are bigger than any dinosaur. True or False?",`,
      `    "format": "true_false",`,
      `    "choices": [`,
      `      { "id": "A", "text": "True", "is_correct": true },`,
      `      { "id": "B", "text": "False", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "At up to 30 meters and 200 tons, the blue whale is the largest animal ever known.",`,
      `    "fun_fact": "A blue whale's tongue alone can weigh as much as an entire adult elephant.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Colossal blue whale swimming gracefully through deep azure ocean with sun rays penetrating the surface",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "age_band": "${ageBand}",`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 5,`,
      `    "tags": ["${options.subtopicId}", "${options.archetypeId}"]`,
      `  }`,
      `]`,
    ].join("\n");
  },

  buildReversePrompt(options: BuildReverseBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";

    return [
      `You are an elite Quiz Architect creating high-retention video trivia for YouTube Shorts & TikTok.`,
      `Your task is to generate exactly ${options.targets.length} questions, strictly mapping 1-to-1 to each target entity provided below.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Gameplay Archetype: "${options.archetypeId}"`,
      `- Format: "true_false"`,
      `- Choice Count: 2`,
      `- Default Thinking Seconds: 5`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Target Language: "${lang}"`,
      ``,
      `=== TARGET ENTITIES (EXACTLY 1 QUESTION PER ENTITY) ===`,
      formatTargetEntitiesBlock(options.targets),
      ``,
      ...SPECIALIZED_TRUE_FALSE_DIRECTIVE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== REVERSE MATRIX GENERATION CONTRACT (STRICT) ===`,
      `1. 1-to-1 MAPPING: Generate exactly ${options.targets.length} questions, in the exact order of the Target Entities.`,
      `2. ENTITY ANCHOR: For each question, set "entity_id" to the corresponding Entity ID.`,
      `3. TRUTH & ACCURACY: Map [TRUE] claims from the target entity to 'True', and [FALSE] claims to 'False'.`,
      `4. CHOICES: Exactly 2 choices with text strictly 'True' and 'False'.`,
      `5. CONCISE HOOK: Question statement ending with '... True or False?' strictly 60 to 80 characters (never exceed 80 chars).`,
      ``,
      ...COMMON_REVERSE_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY JSON OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array of ${options.targets.length} question objects. NO markdown, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "entity_id": "ENT-...",`,
      `    "archetype_id": "${options.archetypeId}",`,
      `    "domain_id": "<target domain>",`,
      `    "subtopic_id": "<target subtopic>",`,
      `    "question": "Punchy factual claim ending with True or False?",`,
      `    "format": "true_false",`,
      `    "choices": [`,
      `      { "id": "A", "text": "True", "is_correct": true },`,
      `      { "id": "B", "text": "False", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "Clear explanation of the verdict.",`,
      `    "fun_fact": "Surprising related fact.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Detailed cinematic visual prompt in English",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 5,`,
      `    "tags": ["<subtopic_id>", "${options.archetypeId}"]`,
      `  }`,
      `]`,
    ].join("\n");
  },
};
