import type {
  ArchetypePromptStrategy,
  BuildBatchPromptOptions,
  BuildReverseBatchPromptOptions,
} from "./promptStrategy.types.js";
import {
  COMMON_BATCH_CONTENT_POLICY_LINES,
  COMMON_REVERSE_CONTENT_POLICY_LINES,
  FRANCHISE_ANCHOR_MANDATE_LINES,
  VISUAL_ANCHOR_MANDATE_LINES,
  formatExistingSamplesBlock,
  formatTargetEntitiesBlock,
} from "./promptCommonBlocks.js";

const VERDICT_ARCHETYPE_ID = "verdict_yes_no";

const SPECIALIZED_YES_NO_DIRECTIVE: string[] = [
  "=== SPECIALIZED YES / NO ARCHETYPE DIRECTIVE (KIDS & FAMILY) ===",
  'CRITICAL RULE: This is the only verdict format. Choices are always exactly "Yes" and "No" (never True / False, Fact / Myth).',
  '1. NATURAL QUESTION: Write a real question a child would ask, opening with Is / Are / Do / Does / Can / Did / Was / Were / Has / Have / Will, and ending with " Yes or No?" (e.g. "Can penguins fly? Yes or No?", "Do octopuses have three hearts? Yes or No?").',
  '2. NEVER A STATEMENT: Never write a declarative claim to be judged (NEVER "Blue whales are bigger than any dinosaur. Yes or No?"). Never write "Is it true that...".',
  "3. ONE CLEAR ANSWER: The answer must be unambiguous and verifiable. Avoid double negatives (\"Isn't it...\"), opinions, trick wording, and sweeping absolutes (always / never / only) unless they are exactly true.",
  "4. KID-FRIENDLY WORDING: Use simple everyday words a 7-year-old understands; keep one idea per question.",
  "5. VERDICT BALANCE: Exactly half of the questions (rounded) must have \"No\" as the correct answer; surprising \"No\" answers that bust a common belief are encouraged.",
  '6. ANCHORING: Map [TRUE] claims from the target entity to correct choice "Yes", and [FALSE] claims to correct choice "No".',
];

export const verdictPromptStrategy: ArchetypePromptStrategy = {
  archetypeId: VERDICT_ARCHETYPE_ID,

  buildBatchPrompt(options: BuildBatchPromptOptions): string {
    const effectiveArchetype = VERDICT_ARCHETYPE_ID;
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";
    const subtopicTitle = options.subtopicTitle || options.subtopicId.replaceAll("_", " ");

    return [
      `You are a world-class Quiz & Trivia Designer for short-form video platforms (YouTube Shorts / TikTok / Reels).`,
      `Your mission is to create exactly ${options.count} unique, high-retention Yes or No questions.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Archetype: "${effectiveArchetype}"`,
      `- Domain: "${options.domainId}"`,
      `- Subtopic: "${options.subtopicId}" ("${subtopicTitle}")`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Language: "${lang}"`,
      `- Format: "yes_no"`,
      `- Choice Count: 2 ("Yes" and "No")`,
      `- Thinking Duration: 5 seconds`,
      `- Core Rules:`,
      `  * Yes or No format. Punchy, natural single-clause question strictly 60 to 80 characters (never exceed 80 chars).`,
      `  * Format: Direct question (Is / Are / Do / Does / Can / Did ...) ending in 'Yes or No?'. Never a statement.`,
      `  * Exactly 2 choices: 'Yes' and 'No'.`,
      `  * Verdict Balance: Maintain a strict ~50/50 balance between Yes and No as the correct choice.`,
      `  * Provide a short, simple explanation along with a surprising real-world fun fact a child can understand.`,
      ``,
      ...SPECIALIZED_YES_NO_DIRECTIVE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== MOBILE VIDEO SHORTS LENGTH & PACING RULES (STRICT) ===`,
      `1. QUESTION LENGTH: Strictly 60 to 80 characters (never exceed 80 chars).`,
      `2. Keep the question punchy and readable under 2 seconds.`,
      ``,
      ...COMMON_BATCH_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array containing ${options.count} question objects. NO markdown fences, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "archetype_id": "${effectiveArchetype}",`,
      `    "domain_id": "${options.domainId}",`,
      `    "subtopic_id": "${options.subtopicId}",`,
      `    "question": "Can a goldfish remember things for months? Yes or No?",`,
      `    "format": "yes_no",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Yes", "is_correct": true },`,
      `      { "id": "B", "text": "No", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "Goldfish can learn tricks and remember them for months, not just 3 seconds.",`,
      `    "fun_fact": "Scientists have trained goldfish to push levers for food at certain times.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Colossal blue whale swimming gracefully through deep azure ocean with sun rays penetrating the surface",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "age_band": "${ageBand}",`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 5,`,
      `    "tags": ["${options.subtopicId}", "${effectiveArchetype}"]`,
      `  }`,
      `]`,
    ].join("\n");
  },

  buildReversePrompt(options: BuildReverseBatchPromptOptions): string {
    const effectiveArchetype = VERDICT_ARCHETYPE_ID;
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";

    return [
      `You are an elite Quiz Architect creating high-retention video trivia for YouTube Shorts & TikTok.`,
      `Your task is to generate exactly ${options.targets.length} questions, strictly mapping 1-to-1 to each target entity provided below.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Gameplay Archetype: "${effectiveArchetype}"`,
      `- Format: "yes_no"`,
      `- Choice Count: 2 ("Yes" and "No")`,
      `- Default Thinking Seconds: 5`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Target Language: "${lang}"`,
      ``,
      `=== TARGET ENTITIES (EXACTLY 1 QUESTION PER ENTITY) ===`,
      formatTargetEntitiesBlock(options.targets),
      ``,
      ...SPECIALIZED_YES_NO_DIRECTIVE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== REVERSE MATRIX GENERATION CONTRACT (STRICT) ===`,
      `1. 1-to-1 MAPPING: Generate exactly ${options.targets.length} questions, in the exact order of the Target Entities.`,
      `2. ENTITY ANCHOR: For each question, set "entity_id" to the corresponding Entity ID.`,
      `3. TRUTH & ACCURACY: Map [TRUE] claims from the target entity to 'Yes', and [FALSE] claims to 'No'.`,
      `4. CHOICES: Exactly 2 choices with text strictly 'Yes' and 'No'.`,
      `5. CONCISE HOOK: Natural question ending with '... Yes or No?' strictly 60 to 80 characters (never exceed 80 chars).`,
      ``,
      ...COMMON_REVERSE_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY JSON OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array of ${options.targets.length} question objects. NO markdown, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "entity_id": "ENT-...",`,
      `    "archetype_id": "${effectiveArchetype}",`,
      `    "domain_id": "<target domain>",`,
      `    "subtopic_id": "<target subtopic>",`,
      `    "question": "Natural kid-friendly question ending with Yes or No?",`,
      `    "format": "yes_no",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Yes", "is_correct": true },`,
      `      { "id": "B", "text": "No", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A (Yes) or B (No), whichever is factually correct",`,
      `    "explanation": "Clear, kid-friendly explanation of the verdict.",`,
      `    "fun_fact": "Surprising related fact.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Detailed cinematic visual prompt in English",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 5,`,
      `    "tags": ["<subtopic_id>", "${effectiveArchetype}"]`,
      `  }`,
      `]`,
    ].join("\n");
  },
};
