import type {
  ArchetypePromptStrategy,
  BuildBatchPromptOptions,
  BuildReverseBatchPromptOptions,
} from "./promptStrategy.types.js";
import {
  COMMON_BATCH_CONTENT_POLICY_LINES,
  COMMON_REVERSE_CONTENT_POLICY_LINES,
  VISUAL_ANCHOR_MANDATE_LINES,
  formatExistingSamplesBlock,
  formatTargetEntitiesBlock,
} from "./promptCommonBlocks.js";

const GOLDEN_VERSUS_FACEOFF_PARADIGMS: string[] = [
  "=== GOLDEN VERSUS FACEOFF PARADIGMS (TRUE HEAD-TO-HEAD SHOWDOWNS) ===",
  "Study these 4 canonical 1v1 showdown styles (natural conversational phrasing strictly 60 to 80 characters, never exceed 80 chars, NO redundant choice suffixes):",
  '1. Natural Franchise Showdown: "In Pixar\'s Cars, who won more Piston Cups?" -> Choices: [A: Lightning McQueen (Correct), B: Doc Hudson].',
  '2. Measurable Stat / Superlative Battle: "Cheetah vs Falcon: Which reaches higher top speed?" -> Choices: [A: Falcon (Correct), B: Cheetah].',
  '3. Shared Arena Dilemma: "In Harry Potter, who escaped Azkaban first?" -> Choices: [A: Sirius Black (Correct), B: Bellatrix Lestrange].',
  '4. Chronological Priority: "Who debuted first in Marvel Comics: Spider-Man or Iron Man?" -> Choices: [A: Spider-Man (Correct), B: Iron Man].',
];

const VERSUS_FRANCHISE_ANCHOR_MANDATE_LINES: string[] = [
  "=== FRANCHISE ANCHOR MANDATE (1v1 VERSUS FORMAT) ===",
  "When generating versus questions about anime, manga, gaming, comics, movies, or fictional characters:",
  "1. NATURAL CONVERSATIONAL PHRASING (PREFERRED):",
  '   - Open with fluent host phrasing: "In [Franchise], who [comparative feat]?" (e.g. "In Pixar\'s Cars, who won more Piston Cups?", "In Harry Potter, who escaped Azkaban first?").',
  '   - Or direct comparative clause: "In [Franchise], between [A] and [B], who [feat]?" (e.g. "In Marvel, between Thor and Hulk, who is stronger?").',
  '   - Cross-Franchise matchup: "[Character A] ([Franchise A]) vs [Character B] ([Franchise B])" (e.g. "Goku (Dragon Ball) vs Saitama (One Punch Man): Who punches harder?").',
  "2. AVOID ROBOTIC DATABASE LABELS: NEVER format questions with stiff prefixes like 'Cars:' or 'Harry Potter:'. Frame questions as natural spoken English for lively video narration.",
  "3. STRICT PROHIBITION AGAINST 1-ENTITY TRIVIA: NEVER write 'In [Franchise], which [entity] [single-entity action]?' where Choice B is an irrelevant bystander (e.g. NEVER write 'In Harry Potter, which wizard escaped Azkaban unaided?' with Snape as distractor). That is a Deep Trivia question, NOT a 1v1 Versus Faceoff!",
  "4. CASUAL RETENTION: Focus comparison on world-famous hallmarks, trophies, records, or signature powers that casual viewers immediately recognize.",
  "5. SHORT UMBRELLA FRANCHISE NAMES ONLY: Always use short umbrella names (e.g. 'In Spider-Man', 'In Cars', 'In Harry Potter'). STRICTLY FORBIDDEN to include lengthy movie subtitles or arc tags to ensure the question fits cleanly within 60 to 80 characters (never exceed 80 chars).",
];

const VERSUS_COMPETITIVE_INTEGRITY_LINES: string[] = [
  "=== 1v1 COMPETITIVE INTEGRITY & SYMMETRY (MANDATORY) ===",
  "1. BOTH CHOICES MUST FIT: Both contenders must legitimately belong to the question's subject category. Never write a question where Choice B is disqualified by definition (e.g. do not ask 'Which red racer...' if Choice B is Tow Mater).",
  "2. NO ASYMMETRIC TRIVIA: Frame questions as active head-to-head showdowns (speed, strength, records, debuts, canon duels) rather than one-sided trivia clues.",
  "3. DILEMMA TENSION: The question must create genuine suspense where viewers have to think about which contender wins.",
];

const SPECIALIZED_VERSUS_FACEOFF_DIRECTIVE: string[] = [
  "=== SPECIALIZED VERSUS FACEOFF COMPARATIVE DIRECTIVE ===",
  "CRITICAL RULES FOR 1v1 HEAD-TO-HEAD COMPARISON:",
  "1. NO REDUNDANT CHOICE TEXT: NEVER append ': Choice A or Choice B?' or '(A or B)' to the question text! Choices A and B are rendered directly on the split-screen buttons.",
  "2. STRICT COMPETITOR SYMMETRY & SHARED PREMISE (MANDATORY):",
  "   - Both Choice A and Choice B MUST legitimately belong to the question's subject category and premise.",
  "   - NEVER write a question whose wording automatically disqualifies Choice B by definition (e.g. NEVER ask 'Which red racer...' when Choice B is Tow Mater — Mater is neither red nor a racer!).",
  "   - NEVER disguise standard 1-entity trivia as a versus faceoff (e.g. NEVER ask 'Which wizard escaped Azkaban unaided?' with Snape as distractor — Snape was never an inmate in Azkaban!).",
  "   - Both contenders must be legitimate peers/rivals competing on a shared dimension (speed, strength, titles, chronological debut, or shared canon event).",
  "3. PEER PAIRING: Set Choice A to the Target Entity name, and Choice B to a true peer/rival from Versus Rivals or Distractor Pool who genuinely competes in the same category.",
  "4. HIGH SYNTACTIC VARIETY & NATURAL HOST VOICE: Rotate across these comparative styles:",
  '   - Natural Franchise Hook: "In [Franchise], who [won more titles / achieved milestone]?" (e.g. "In Pixar\'s Cars, who won more Piston Cups?")',
  '   - Stat / Superlative Showdown: "[Entity A] vs [Entity B]: Who has higher [speed / stat]?"',
  '   - Shared Arena Clash: "In [Franchise], who [escaped / survived / won] first?" (e.g. "In Harry Potter, who escaped Azkaban first?")',
  '   - Chronological Priority: "Who debuted first / was founded earlier: [Entity A] or [Entity B]?"',
  "5. LENGTH: Keep question strictly 60 to 80 characters (never exceed 80 chars) so it renders crisply above the split cards without text clipping.",
];

export const versusFaceoffPromptStrategy: ArchetypePromptStrategy = {
  archetypeId: "versus_faceoff",

  buildBatchPrompt(options: BuildBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";
    const subtopicTitle = options.subtopicTitle || options.subtopicId.replaceAll("_", " ");

    return [
      `You are a world-class Quiz & Trivia Designer for short-form video platforms (YouTube Shorts / TikTok / Reels).`,
      `Your mission is to create exactly ${options.count} unique 1v1 head-to-head showdown questions.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Archetype: "versus_faceoff"`,
      `- Domain: "${options.domainId}"`,
      `- Subtopic: "${options.subtopicId}" ("${subtopicTitle}")`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Language: "${lang}"`,
      `- Format: "multiple_choice"`,
      `- Choice Count: 2`,
      `- Thinking Duration: 5 seconds`,
      ``,
      ...GOLDEN_VERSUS_FACEOFF_PARADIGMS,
      ``,
      ...VERSUS_FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VERSUS_COMPETITIVE_INTEGRITY_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== MOBILE VIDEO SHORTS LENGTH & PACING RULES (STRICT) ===`,
      `1. QUESTION LENGTH: Strictly 60 to 80 characters (never exceed 80 chars).`,
      `2. NEVER append ': Choice A or Choice B?' to question text. Choices are rendered on split cards.`,
      ``,
      ...COMMON_BATCH_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array containing ${options.count} question objects. NO markdown fences, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "archetype_id": "versus_faceoff",`,
      `    "domain_id": "${options.domainId}",`,
      `    "subtopic_id": "${options.subtopicId}",`,
      `    "question": "Cheetah vs Falcon: Which reaches higher top speed?",`,
      `    "format": "multiple_choice",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Falcon", "is_correct": true },`,
      `      { "id": "B", "text": "Cheetah", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "The Peregrine Falcon dives at over 320 km/h, far surpassing the Cheetah's top speed of 120 km/h.",`,
      `    "fun_fact": "Peregrine falcons have special nostrils to breathe during high-speed dives.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Split confrontation scene with a diving peregrine falcon and a sprinting cheetah",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "age_band": "${ageBand}",`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 5,`,
      `    "tags": ["${options.subtopicId}", "versus_faceoff"]`,
      `  }`,
      `]`,
    ].join("\n");
  },

  buildReversePrompt(options: BuildReverseBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";

    return [
      `You are an elite Quiz Architect creating high-retention video trivia for YouTube Shorts & TikTok.`,
      `Your task is to generate exactly ${options.targets.length} questions, strictly mapping 1-to-1 to each target entity provided below.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Gameplay Archetype: "versus_faceoff"`,
      `- Format: "multiple_choice"`,
      `- Choice Count: 2`,
      `- Default Thinking Seconds: 5`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Target Language: "${lang}"`,
      ``,
      `=== TARGET ENTITIES (EXACTLY 1 QUESTION PER ENTITY) ===`,
      formatTargetEntitiesBlock(options.targets),
      ``,
      ...SPECIALIZED_VERSUS_FACEOFF_DIRECTIVE,
      ``,
      ...VERSUS_FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== REVERSE MATRIX GENERATION CONTRACT (STRICT) ===`,
      `1. 1-to-1 MAPPING: Generate exactly ${options.targets.length} questions, in the exact order of the Target Entities.`,
      `2. ENTITY ANCHOR: For each question, set "entity_id" to the corresponding Entity ID.`,
      `3. COMPARATIVE TRUTH & ACCURACY: Base the question directly on a head-to-head showdown, verified stat, record, or shared milestone between Target Entity and Rival.`,
      `4. SYMMETRIC RIVAL PAIRING: Set Choice B to a rival from Versus Rivals or Distractor Pool who shares the same domain/role so the matchup is credible.`,
      `5. NO ONE-SIDED TRIVIA: Do NOT just pick an isolated fact of Target Entity and slap a random rival into Choice B. The question premise MUST make viewers pause and compare both contenders.`,
      `6. CONCISE HOOK: Question text must be strictly 60 to 80 characters (never exceed 80 chars) without choice suffixes.`,
      ``,
      ...COMMON_REVERSE_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY JSON OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array of ${options.targets.length} question objects. NO markdown, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "entity_id": "ENT-...",`,
      `    "archetype_id": "versus_faceoff",`,
      `    "domain_id": "<target domain>",`,
      `    "subtopic_id": "<target subtopic>",`,
      `    "question": "Direct comparison question text?",`,
      `    "format": "multiple_choice",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Target Entity Name", "is_correct": true },`,
      `      { "id": "B", "text": "Rival Entity Name", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "Clear explanation of the winning record or verified fact.",`,
      `    "fun_fact": "Surprising related fact.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Split confrontation scene with both entities",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 5,`,
      `    "tags": ["<subtopic_id>", "versus_faceoff"]`,
      `  }`,
      `]`,
    ].join("\n");
  },
};
