import type {
  ArchetypePromptStrategy,
  BuildBatchPromptOptions,
  BuildReverseBatchPromptOptions,
} from "./promptStrategy.types.js";
import {
  COMMON_BATCH_CONTENT_POLICY_LINES,
  COMMON_REVERSE_CONTENT_POLICY_LINES,
  FRANCHISE_ANCHOR_MANDATE_LINES,
  VISUAL_ANCHOR_MANDATE_LINES,
  formatExistingSamplesBlock,
  formatTargetEntitiesBlock,
} from "./promptCommonBlocks.js";
import {
  allocateVisualSpottingSeeds,
  formatVisualSpottingSeedsBlock,
} from "./visualSpottingSeedCatalog.js";

const GOLDEN_VISUAL_SPOTTING_PARADIGMS: string[] = [
  "=== GOLDEN VISUAL SPOTTING PARADIGMS (ANTI-REPETITION EXAMPLES) ===",
  'Study these 5 varied spotting hooks (NEVER repeat "is the odd one out" or robotic suffixes like "spot the mismatch"):',
  '1. Dual-Trait Dilemma: "Two are deadly venomous, but which one is harmless?"',
  '2. Group mismatch: "One of these Greek voyagers doesn\'t fit — can you spot it?"',
  '3. Outlier challenge: "Which of these three mythical relics is the outlier?"',
  '4. Exception finder: "Find the exception among these ancient champions!"',
  '5. Impostor alert: "Spot the impostor: Which Norse goddess does not belong?"',
];

const MACROSCOPIC_EDUTAINMENT_CONTRAST_MANDATE: string[] = [
  "=== MACROSCOPIC EDUTAINMENT CONTRAST MANDATE (CASUAL & FAMILY AUDIENCE) ===",
  "CRITICAL RULE FOR EDUTAINMENT RETENTION & IMMEDIATE DOPAMINE:",
  "Viewers have only 5 to 7 seconds on mobile screens. The anomaly MUST be based on bold, universally recognizable macroscopic contrasts:",
  "1. Diet & Nutrition: 2 Carnivores / Predators vs 1 Herbivore / Vegetarian (e.g. Lion & Wolf vs Giant Panda).",
  "2. Habitat & Climate: 2 Polar / Arctic dwellers vs 1 Desert / Tropical dweller (e.g. Polar Bear & Emperor Penguin vs Fennec Fox).",
  "3. Locomotion & Physics: 2 Flying birds vs 1 Flightless bird (e.g. Falcon & Eagle vs Ostrich / Penguin).",
  "4. Prominent Physical Hallmarks: 2 Horned/Antlered creatures vs 1 Hornless; 2 Striped creatures vs 1 Spotted.",
  "5. Pop-Culture / Power Origin: In fictional universes, 2 Superpowered / Mutants vs 1 Regular human using tech (e.g. Thor & Hulk vs Iron Man).",
  "STRICTLY FORBIDDEN (MICRO-SCIENTIFIC & ACADEMIC TRIVIA):",
  "- NEVER base the outlier on microscopic anatomy, claw retractability, dental formulas, chromosome counts, or obscure taxonomic classifications.",
  "- NEVER require a biology, zoology, or history PhD to solve the puzzle.",
  "- After the answer is revealed, a 10-12 year old or casual viewer MUST immediately react with: 'Aha! That makes total sense!'.",
];

const SPECIALIZED_VISUAL_SPOTTING_DIRECTIVE: string[] = [
  "=== SPECIALIZED VISUAL SPOTTING OUTLIER DIRECTIVE ===",
  "CRITICAL RULES FOR VISUAL SPOTTING (ODD ONE OUT):",
  '1. ANTI-MONOTONY MANDATE & ZERO "ODD ONE OUT" TOLERANCE: STRICTLY FORBIDDEN to use the literal phrase "odd one out" or repetitive formulas like "... is the odd one out?" or append robotic canned suffixes like "— spot the mismatch!". Frame questions as natural, engaging dilemmas that embed the contrast directly into the subject matter.',
  "2. HOOK VARIETY ROTATION: Rotate continuously across the allocated diversity blueprints provided below.",
  "3. ANCHORING: The correct choice is the anomaly/outlier, while the 2 distractors share a common theme/trait from the entity's domain.",
];

export const visualSpottingPromptStrategy: ArchetypePromptStrategy = {
  archetypeId: "visual_spotting",

  buildBatchPrompt(options: BuildBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";
    const subtopicTitle = options.subtopicTitle || options.subtopicId.replaceAll("_", " ");
    const seeds = allocateVisualSpottingSeeds(options.count, options.domainId);

    return [
      `You are a world-class Visual Puzzle & Odd-One-Out Designer for short-form video platforms (YouTube Shorts / TikTok / Reels).`,
      `Your mission is to create exactly ${options.count} unique, high-retention Visual Spotting challenges.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Archetype: "visual_spotting"`,
      `- Domain: "${options.domainId}"`,
      `- Subtopic: "${options.subtopicId}" ("${subtopicTitle}")`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Language: "${lang}"`,
      `- Format: "odd_one_out"`,
      `- Choice Count: 3 (Cards A, B, C)`,
      `- Thinking Duration: 6 seconds`,
      ``,
      formatVisualSpottingSeedsBlock(seeds),
      ``,
      ...SPECIALIZED_VISUAL_SPOTTING_DIRECTIVE,
      ``,
      ...GOLDEN_VISUAL_SPOTTING_PARADIGMS,
      ``,
      ...MACROSCOPIC_EDUTAINMENT_CONTRAST_MANDATE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== MOBILE VIDEO SHORTS LENGTH & PACING RULES (STRICT) ===`,
      `1. QUESTION LENGTH: Strictly 6 to 12 words (40–75 characters max).`,
      `2. Keep the question punchy, readable under 2 seconds on mobile vertical screens.`,
      `3. Reserve the full logical explanation strictly for the "explanation" field.`,
      ``,
      ...COMMON_BATCH_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array containing ${options.count} question objects. NO markdown fences, NO commentary outside the array.`,
      `JSON structure for each question:`,
      `[`,
      `  {`,
      `    "archetype_id": "visual_spotting",`,
      `    "domain_id": "${options.domainId}",`,
      `    "subtopic_id": "${options.subtopicId}",`,
      `    "question": "Two are deadly venomous, but which one is harmless?",`,
      `    "format": "odd_one_out",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Outlier Entity Name", "is_correct": true },`,
      `      { "id": "B", "text": "Matching Entity 1", "is_correct": false },`,
      `      { "id": "C", "text": "Matching Entity 2", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "Clear 1-2 sentence explanation of why Choice A is the anomaly while B and C share the common macroscopic trait.",`,
      `    "fun_fact": "Surprising related trivia fact.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Detailed cinematic visual prompt in English describing the 3 distinct subjects",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "age_band": "${ageBand}",`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 6,`,
      `    "tags": ["${options.subtopicId}", "visual_spotting"]`,
      `  }`,
      `]`,
    ].join("\n");
  },

  buildReversePrompt(options: BuildReverseBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";
    const seeds = allocateVisualSpottingSeeds(options.targets.length, options.targets[0]?.domain_id);

    return [
      `You are an elite Quiz Architect creating high-retention Visual Spotting challenges for YouTube Shorts & TikTok.`,
      `Your task is to generate exactly ${options.targets.length} questions, strictly mapping 1-to-1 to each target entity provided below.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Gameplay Archetype: "visual_spotting"`,
      `- Format: "odd_one_out"`,
      `- Choice Count: 3`,
      `- Default Thinking Seconds: 6`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Target Language: "${lang}"`,
      ``,
      `=== TARGET ENTITIES (EXACTLY 1 QUESTION PER ENTITY) ===`,
      formatTargetEntitiesBlock(options.targets),
      ``,
      formatVisualSpottingSeedsBlock(seeds),
      ``,
      ...SPECIALIZED_VISUAL_SPOTTING_DIRECTIVE,
      ``,
      ...MACROSCOPIC_EDUTAINMENT_CONTRAST_MANDATE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== REVERSE MATRIX GENERATION CONTRACT (STRICT) ===`,
      `1. 1-to-1 MAPPING: Generate exactly ${options.targets.length} questions, in the exact order of the Target Entities.`,
      `2. ENTITY ANCHOR: For each question, set "entity_id" to the corresponding Entity ID.`,
      `3. TRUTH & ACCURACY: Base the question directly on verified traits or rivals. Do NOT hallucinate facts.`,
      `4. DISTRACTORS: Draw 2 plausible matching choices sharing a clear common trait so the target is the obvious macroscopic anomaly.`,
      `5. CONCISE HOOK: Question text must be strictly 6 to 12 words (40-75 characters max).`,
      ``,
      ...COMMON_REVERSE_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY JSON OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array of ${options.targets.length} question objects. NO markdown, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "entity_id": "ENT-...",`,
      `    "archetype_id": "visual_spotting",`,
      `    "domain_id": "<target domain>",`,
      `    "subtopic_id": "<target subtopic>",`,
      `    "question": "Two are apex carnivores, but which one is a peaceful vegetarian?",`,
      `    "format": "odd_one_out",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Target Anomaly Entity", "is_correct": true },`,
      `      { "id": "B", "text": "Distractor 1", "is_correct": false },`,
      `      { "id": "C", "text": "Distractor 2", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "Clear explanation of the macroscopic trait contrast.",`,
      `    "fun_fact": "Surprising related fact.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Detailed cinematic visual prompt in English",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 6,`,
      `    "tags": ["<subtopic_id>", "visual_spotting"]`,
      `  }`,
      `]`,
    ].join("\n");
  },
};
