import type {
  ArchetypePromptStrategy,
  BuildBatchPromptOptions,
  BuildReverseBatchPromptOptions,
} from "./promptStrategy.types.js";
import {
  COMMON_BATCH_CONTENT_POLICY_LINES,
  COMMON_REVERSE_CONTENT_POLICY_LINES,
  FRANCHISE_ANCHOR_MANDATE_LINES,
  VISUAL_ANCHOR_MANDATE_LINES,
  formatExistingSamplesBlock,
  formatTargetEntitiesBlock,
} from "./promptCommonBlocks.js";

const GOLDEN_VISUAL_IDENTIFICATION_PARADIGMS: string[] = [
  "=== GOLDEN VISUAL IDENTIFICATION PARADIGMS (RECOGNITION EXAMPLES) ===",
  "Study these 4 visual identification styles:",
  '1. Phenomenon naming: "What do astronomers call the point of no return around a black hole?" -> [A: Event Horizon (Correct), B: Ergosphere, C: Accretion Disk]',
  '2. Clue teaser: "Smelled like gunpowder to Apollo astronauts — what is this dust?" -> [A: Lunar Regolith (Correct), B: Basalt Ash, C: Cosmic Silt]',
  '3. Cosmic feature: "Can you recognize the supermassive black hole at our galactic core?" -> [A: Sagittarius A* (Correct), B: Cygnus X-1, C: M87*]',
  '4. Solar phenomenon: "What glowing loop of magnetic plasma arches off the Sun?" -> [A: Solar Prominence (Correct), B: Solar Flare, C: Coronal Loop]',
];

const SPECIALIZED_VISUAL_IDENTIFICATION_DIRECTIVE: string[] = [
  "=== SPECIALIZED VISUAL IDENTIFICATION DIRECTIVE ===",
  "CRITICAL RULES FOR VISUAL IDENTIFICATION:",
  "1. SYNTACTIC DIVERSITY: DO NOT start every question with 'What [adjective] [noun]...' or 'Which [noun]...'. Vary the grammatical opening continuously.",
  "2. RECOGNITION HOOK ROTATION: Rotate across these 5 phrasing patterns:",
  '   - Phenomenon naming: "What do astronomers call the point of no return around a black hole?"',
  '   - Direct recognition: "Can you identify this [creature / landmark / wonder]?"',
  '   - Clue teaser: "Known for [surprising trait] — what is this [creature / landmark]?"',
  '   - Category locator: "Which [iconic landmark / wonder] anchors [location]?"',
  '   - Feature detective: "Identify this [subject] from its distinctive [physical trait]."',
  "3. ANCHORING: Focus on the entity's visual_anchor and distinctive physical traits.",
];

const FAMILY_EDUTAINMENT_VISUAL_ID_MANDATE: string[] = [
  "=== FAMILY-FRIENDLY VISUAL IDENTIFICATION MANDATE (NO ACADEMIC JARGON / NO OBSCURE SUBSPECIES) ===",
  "CRITICAL RULES FOR CASUAL FAMILY & KIDS RETENTION (EDUTAINMENT FOCUS):",
  "1. FORBIDDEN - ACADEMIC / SCIENTIST DISCIPLINE CALLOUTS:",
  "   - NEVER start questions with obscure academic discipline callouts (e.g. NEVER ask 'What do entomologists call...', 'What do herpetologists call...', 'What do ichthyologists call...').",
  "   - Frame questions naturally and invitingly: 'Can you identify this [subject]?', 'Which famous creature...', 'Known for its glowing blue wings, what is this rainforest creature?'.",
  "2. FORBIDDEN - OBSCURE SUBSPECIES & LATIN TAXONOMY BATTLES:",
  "   - NEVER pit obscure, near-identical insect subspecies against each other (e.g. NEVER Atlas Moth vs Luna Moth vs Domestic Silk Moth).",
  "   - NEVER test niche scientific taxonomy that even educated adults cannot answer in 5 seconds.",
  "   - The target entity and all 3 choices MUST be HIGH-RECOGNITION HOUSEHOLD ENTITIES (e.g. Praying Mantis, Monarch Butterfly, Honeybee, Chameleon, Colosseum, Saturn).",
  "3. ICONIC VISUAL ANCHORING (SEE IT -> KNOW IT):",
  "   - The visual clue must point to a famous, recognizable hallmark of a well-known subject (e.g. scythe-arms of a praying mantis, 3,000-mile migration of a monarch butterfly, spiraled tusk of a narwhal).",
  "4. STRICT MOBILE QUESTION BREVITY (STRICTLY 60–80 CHARACTERS):",
  "   - On 9:16 vertical mobile screens, the question box fits at most 2 lines without font shrinkage.",
  "   - Keep question text strictly 60 to 80 characters (never exceed 80 chars) so it can be read and grasped in under 2 seconds.",
  "   - Reserve rich bonus details strictly for the 'explanation' and 'fun_fact' fields!",
];

export const visualIdentificationPromptStrategy: ArchetypePromptStrategy = {
  archetypeId: "visual_identification",

  buildBatchPrompt(options: BuildBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";
    const subtopicTitle = options.subtopicTitle || options.subtopicId.replaceAll("_", " ");

    return [
      `You are a world-class Visual Recognition & Identification Quiz Designer for short-form video platforms (YouTube Shorts / TikTok / Reels).`,
      `Your mission is to create exactly ${options.count} unique, high-retention Visual Identification questions.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Archetype: "visual_identification"`,
      `- Domain: "${options.domainId}"`,
      `- Subtopic: "${options.subtopicId}" ("${subtopicTitle}")`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Language: "${lang}"`,
      `- Format: "multiple_choice"`,
      `- Choice Count: 3`,
      `- Thinking Duration: 5 seconds`,
      ``,
      ...GOLDEN_VISUAL_IDENTIFICATION_PARADIGMS,
      ``,
      ...FAMILY_EDUTAINMENT_VISUAL_ID_MANDATE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== MOBILE VIDEO SHORTS LENGTH & PACING RULES (STRICT) ===`,
      `1. QUESTION LENGTH: Strictly 60 to 80 characters (never exceed 80 chars). Must fit in 2 lines on mobile vertical screens.`,
      `2. PUNCHY HOOK ONLY: Keep question text readable under 2 seconds. Move all background narrative to explanation.`,
      ``,
      ...COMMON_BATCH_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array containing ${options.count} question objects. NO markdown fences, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "archetype_id": "visual_identification",`,
      `    "domain_id": "${options.domainId}",`,
      `    "subtopic_id": "${options.subtopicId}",`,
      `    "question": "What do astronomers call the point of no return around a black hole?",`,
      `    "format": "multiple_choice",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Event Horizon", "is_correct": true },`,
      `      { "id": "B", "text": "Ergosphere", "is_correct": false },`,
      `      { "id": "C", "text": "Accretion Disk", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "The event horizon marks the boundary where escape velocity equals the speed of light.",`,
      `    "fun_fact": "Nothing, not even light, can escape once past the event horizon.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Cinematic visual closeup of a supermassive black hole with glowing fiery accretion disk",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "age_band": "${ageBand}",`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 5,`,
      `    "tags": ["${options.subtopicId}", "visual_identification"]`,
      `  }`,
      `]`,
    ].join("\n");
  },

  buildReversePrompt(options: BuildReverseBatchPromptOptions): string {
    const lang = options.language || "en";
    const diff = options.difficulty ?? 2;
    const ageBand = options.ageBand || "family";

    return [
      `You are an elite Quiz Architect creating high-retention video trivia for YouTube Shorts & TikTok.`,
      `Your task is to generate exactly ${options.targets.length} questions, strictly mapping 1-to-1 to each target entity provided below.`,
      ``,
      `=== ASSIGNMENT PARAMETERS ===`,
      `- Gameplay Archetype: "visual_identification"`,
      `- Format: "multiple_choice"`,
      `- Choice Count: 3`,
      `- Default Thinking Seconds: 5`,
      `- Target Difficulty: ${diff}/5`,
      `- Target Age Band: "${ageBand}"`,
      `- Target Language: "${lang}"`,
      ``,
      `=== TARGET ENTITIES (EXACTLY 1 QUESTION PER ENTITY) ===`,
      formatTargetEntitiesBlock(options.targets),
      ``,
      ...SPECIALIZED_VISUAL_IDENTIFICATION_DIRECTIVE,
      ``,
      ...FAMILY_EDUTAINMENT_VISUAL_ID_MANDATE,
      ``,
      ...FRANCHISE_ANCHOR_MANDATE_LINES,
      ``,
      ...VISUAL_ANCHOR_MANDATE_LINES,
      ``,
      `=== REVERSE MATRIX GENERATION CONTRACT (STRICT) ===`,
      `1. 1-to-1 MAPPING: Generate exactly ${options.targets.length} questions, in the exact order of the Target Entities.`,
      `2. ENTITY ANCHOR: For each question, set "entity_id" to the corresponding Entity ID.`,
      `3. TRUTH & ACCURACY: Base the question directly on verified traits or visual appearance.`,
      `4. DISTRACTORS: Draw plausible choices from high-recognition entities in the domain. NEVER pit obscure subspecies against each other.`,
      `5. CONCISE HOOK: Strictly 60 to 80 characters (never exceed 80 chars) to fit 2 lines on mobile screens.`,
      ``,
      ...COMMON_REVERSE_CONTENT_POLICY_LINES,
      formatExistingSamplesBlock(options.existingQuestionSamples),
      `=== MANDATORY JSON OUTPUT FORMAT ===`,
      `Return ONLY a valid JSON array of ${options.targets.length} question objects. NO markdown, NO commentary outside the array.`,
      `[`,
      `  {`,
      `    "entity_id": "ENT-...",`,
      `    "archetype_id": "visual_identification",`,
      `    "domain_id": "<target domain>",`,
      `    "subtopic_id": "<target subtopic>",`,
      `    "question": "Can you identify this famous rainforest creature?",`,
      `    "format": "multiple_choice",`,
      `    "choices": [`,
      `      { "id": "A", "text": "Target Entity Name", "is_correct": true },`,
      `      { "id": "B", "text": "Household Distractor 1", "is_correct": false },`,
      `      { "id": "C", "text": "Household Distractor 2", "is_correct": false }`,
      `    ],`,
      `    "correct_choice_id": "A",`,
      `    "explanation": "Clear explanation of the identifying traits.",`,
      `    "fun_fact": "Surprising related fact.",`,
      `    "visual_spec": {`,
      `      "intent": "question_illustration",`,
      `      "prompt": "Detailed cinematic visual prompt in English",`,
      `      "aspect_ratio": "16:9"`,
      `    },`,
      `    "difficulty": ${diff},`,
      `    "thinking_seconds": 5,`,
      `    "tags": ["<subtopic_id>", "visual_identification"]`,
      `  }`,
      `]`,
    ].join("\n");
  },
};
