import {
  listMascots,
  getMascot,
  saveMascot,
  deleteMascot,
  saveMascotAsset,
  getMascotAssetFile,
  calibrateMascotAction,
  listMascotAssets,
  deleteMascotAssetFile,
  assignMascotToChannel,
  createMascotStyle,
  updateMascotStyle,
  deleteMascotStyle,
  updateMascotSlot,
  setActiveMascotStyle,
} from "../mascots.js";

export const mascotBindings = {
  listMascots,
  getMascot,
  saveMascot,
  deleteMascot,
  saveMascotAsset,
  getMascotAssetFile,
  calibrateMascotAction,
  listMascotAssets,
  deleteMascotAssetFile,
  assignMascotToChannel,
  createMascotStyle,
  updateMascotStyle,
  deleteMascotStyle,
  updateMascotSlot,
  setActiveMascotStyle,
};
