import type { MascotDialogueSeedEntry } from "./dialogueTypes.js";

export const OUTRO_DIALOGUE_BY_SEED: Record<string, MascotDialogueSeedEntry> = {
  F01: {
    text: "Subscribe for more quizzes! See you next round!",
    delivery: "The mascot gives a warm, friendly invitation with synchronized lip-sync and a cheerful goodbye",
    secondaryText: "See ya next time! Bye-bye!",
    secondaryDelivery: "Warm and affectionate sign-off with friendly wave",
  },
  F02: {
    text: "Play again soon! Subscribe for daily trivia!",
    delivery: "The mascot waves invitingly while speaking cheerfully with clear lip-sync",
    secondaryText: "See you on the next quiz!",
    secondaryDelivery: "Affectionate goodbye smile",
  },
  F03: {
    text: "Awesome job today! Subscribe and keep shining!",
    delivery: "The mascot celebrates the viewer with proud delight and clear lip-sync",
    secondaryText: "Catch you later! Keep shining!",
    secondaryDelivery: "Playful wink and wave",
  },
  F04: {
    text: "Ready for more? Subscribe to test your skills!",
    delivery: "The mascot teases the next quiz excitedly with clear lip-sync",
    secondaryText: "See ya at the next round!",
    secondaryDelivery: "Energetic fist pump and wave",
  },
  F05: {
    text: "More puzzles coming! Subscribe to never miss out!",
    delivery: "The mascot shares a playful teaser with a broad smile and clear lip-sync",
    secondaryText: "Don't miss it! Bye-bye!",
    secondaryDelivery: "Warm farewell nod and wave",
  },
  F06: {
    text: "Thanks for playing! Subscribe for our next quest!",
    delivery: "The mascot gives a sincere, happy sign-off with clear synchronized lip-sync",
    secondaryText: "Catch ya next time!",
    secondaryDelivery: "Affectionate two-handed wave",
  },
  F07: {
    text: "Join our quiz crew! Subscribe to play daily!",
    delivery: "The mascot delivers a warm community farewell with clear synchronized lip-sync",
    secondaryText: "See you real soon!",
    secondaryDelivery: "Bright smile and playful bounce",
  },
  F08: {
    text: "Tap subscribe for your next brain quest!",
    delivery: "The mascot enthusiastically invites viewers to join the squad with vibrant smile and clear lip-sync",
    secondaryText: "See ya next time! Bye-bye!",
    secondaryDelivery: "Affectionate wave directly to camera",
  },
  F09: {
    text: "Level up! Hit subscribe to train together!",
    delivery: "The mascot delivers an energetic motivational call with confident gestures and synchronized lip-sync",
    secondaryText: "Catch you later! Keep shining!",
    secondaryDelivery: "Bright wink and cheerful salute",
  },
  F10: {
    text: "Hungry for brain snacks? Subscribe for daily bites!",
    delivery: "The mascot teases with playful, humorous charm and expressive lip-sync",
    secondaryText: "See ya soon, puzzle champion!",
    secondaryDelivery: "Warm smile and friendly wave",
  },
  F11: {
    text: "Join our quiz squad! Subscribe to play along!",
    delivery: "The mascot points proudly toward the logo with high-energy excitement and clear lip-sync",
    secondaryText: "Catch you on the next adventure! Bye!",
    secondaryDelivery: "Energetic goodbye wave",
  },
  F12: {
    text: "Tricky quiz? Subscribe for tomorrow's mystery challenge!",
    delivery: "The mascot poses a cheeky, mysterious challenge with curious eye animation and clear lip-sync",
    secondaryText: "Get ready! Bye-bye!",
    secondaryDelivery: "Affectionate wave with anticipating smile",
  },
  F13: {
    text: "Want a perfect score? Subscribe and find out!",
    delivery: "The mascot issues a spirited, smiling challenge directly to the camera with sharp lip-sync",
    secondaryText: "See ya at the showdown! Bye!",
    secondaryDelivery: "Playful bounce and farewell wave",
  },
  F14: {
    text: "Brain buster coming soon! Subscribe to stay ready!",
    delivery: "The mascot hypes up the upcoming challenge with wide-eyed excitement and clear lip-sync",
    secondaryText: "Catch ya soon! Bye-bye!",
    secondaryDelivery: "Warm living smile locked on the lens",
  },
  F15: {
    text: "Lightning challenge next! Subscribe to test your speed!",
    delivery: "The mascot delivers a punchy, rapid-fire invitation with dynamic posture and clear lip-sync",
    secondaryText: "Keep thinking fast! See ya!",
    secondaryDelivery: "Snappy finger-snap or cute wave",
  },
  F16: {
    text: "Beat the riddle master! Subscribe and play along!",
    delivery: "The mascot teases an adventurous quest with confident swagger and clear lip-sync",
    secondaryText: "See ya next time! Bye!",
    secondaryDelivery: "Warm farewell salute",
  },
  F17: {
    text: "How many right? Comment your score below!",
    delivery: "The mascot leans in curiously with an open gesture asking for comments with clear lip-sync",
    secondaryText: "Can't wait to see your score! Bye-bye!",
    secondaryDelivery: "Friendly wave and warm eye contact",
  },
  F18: {
    text: "Trickiest question today? Comment below and subscribe!",
    delivery: "The mascot scratches head playfully then smiles broadly with clear lip-sync",
    secondaryText: "You did great today! See ya!",
    secondaryDelivery: "Proud nod and cheerful wave",
  },
  F19: {
    text: "Quiz champion! Share your score down below!",
    delivery: "The mascot crowns the viewer with enthusiastic thumbs-up and synchronized lip-sync",
    secondaryText: "Catch you on the next challenge!",
    secondaryDelivery: "Heroic pose with living smile",
  },
  F20: {
    text: "Beat my score? Tell me in the comments!",
    delivery: "The mascot tilts head playfully with an inviting smile and synchronized lip-sync",
    secondaryText: "See ya on the leaderboard! Bye!",
    secondaryDelivery: "Joyful wave with affectionate gaze",
  },
  F21: {
    text: "What topic next? Comment below and subscribe!",
    delivery: "The mascot reaches toward the audience with genuine curiosity and clear lip-sync",
    secondaryText: "I'll be reading your ideas! Bye-bye!",
    secondaryDelivery: "Warm, respectful closing wave",
  },
  F22: {
    text: "My head is spinning! Subscribe for more fun!",
    delivery: "The mascot playfully fans itself with comic relief before flashing a cheerful grin and clear lip-sync",
    secondaryText: "Gotta cool down now! See ya!",
    secondaryDelivery: "Chuckle and cute farewell wave",
  },
  F23: {
    text: "Air high-five! Subscribe so we keep playing!",
    delivery: "The mascot slaps an enthusiastic air high-five toward the camera lens with clear lip-sync",
    secondaryText: "You rock! Catch ya later!",
    secondaryDelivery: "Two thumbs up and a bright smile",
  },
  F24: {
    text: "Great brain workout! Subscribe to stay sharp!",
    delivery: "The mascot flexes playfully with athletic cartoon energy and synchronized lip-sync",
    secondaryText: "Catch you at the next workout! Bye-bye!",
    secondaryDelivery: "Playful bounce and living smile",
  },
  F25: {
    text: "Spark of genius! Subscribe to join the fun!",
    delivery: "The mascot gestures with glowing admiration and warm, delighted facial expression with clear lip-sync",
    secondaryText: "Stay brilliant! See ya next time!",
    secondaryDelivery: "Gentle wave and sparkling smile",
  },
  F26: {
    text: "Victory dance! Subscribe for more quiz adventures!",
    delivery: "The mascot performs a quick celebratory wiggle while delivering the invite with clear lip-sync",
    secondaryText: "Dance on! See ya soon, bye-bye!",
    secondaryDelivery: "Rhythmic bounce and enthusiastic wave",
  },
  F27: {
    text: "Curious minds! Subscribe to discover daily quizzes!",
    delivery: "The mascot speaks with infectious curiosity and bright, wide-eyed wonder with clear lip-sync",
    secondaryText: "Never stop wondering! Bye-bye!",
    secondaryDelivery: "Warm nod and enduring smile",
  },
  F28: {
    text: "Subscribe to stay sharp, curious, and awesome!",
    delivery: "The mascot delivers a motivational catchphrase with punchy rhythm and clear synchronized lip-sync",
    secondaryText: "Catch you on the next quiz! Peace out!",
    secondaryDelivery: "Playful peace sign or friendly wave",
  },
  F29: {
    text: "Knowledge is superpower! Subscribe to level up daily!",
    delivery: "The mascot radiates triumphant hero energy with confident, inspiring lip-sync",
    secondaryText: "Keep shining, superstar! Bye-bye!",
    secondaryDelivery: "Affectionate salute and living smile",
  },
  F30: {
    text: "Unforgettable challenge tomorrow! Tap subscribe and join in!",
    delivery: "The mascot leans forward with eager anticipation and a bright, radiant smile with clear lip-sync",
    secondaryText: "Can't wait to see you! Bye-bye!",
    secondaryDelivery: "Warm, lingering two-handed farewell wave",
  },
};
