import type { CreativeSeed } from "@studio/shared";
import { buildSeedsFromDefinitions, type SeedDefinition } from "./seedTypes.js";

export const INTRO_SEED_DEFINITIONS: Record<string, SeedDefinition[]> = {
  intro_entrance: [
    ["A01", "Energetic Arrival", "Enter already in full active motion with a clear burst of friendly energy using supported locomotion."],
    ["A02", "Edge Reveal", "Reveal the mascot playfully from a frame edge without hiding signature features."],
    ["A03", "Light Reveal", "Reveal the mascot through a clean light or particle transition."],
    ["A04", "Supported Ride", "Arrive using a small safe ride suited to the mascot's body and style."],
    ["A05", "Container Reveal", "Reveal the mascot from an oversized soft container without compressing rigid features."],
    ["A06", "Camera Greeting", "Acknowledge the camera with a supported greeting gesture."],
    ["A07", "Attention Shift", "Enter already in curious motion, reacting with delight to the start of the quiz."],
    [
      "A08",
      "Dynamic Chase Hook",
      "Dash or slide into frame chasing a dynamic glowing cue or energetic element suited to the mascot's style.",
      ["locomotion"],
    ],
    [
      "A09",
      "Superhero Landing",
      "Descend or leap dynamically into the frame with an energetic superhero landing that shakes the view before stabilizing.",
      ["locomotion"],
    ],
    [
      "A10",
      "Sneaker Skid Stop",
      "Sprint into frame and perform a playful shoe-skid stop, creating subtle sparkly friction cues before engaging the camera.",
      ["locomotion"],
    ],
    [
      "A11",
      "Peek-a-Boo Surprise",
      "Pop playfully into frame from behind a scenic element or stage prop, startling the camera in a delightful way.",
    ],
    [
      "A12",
      "Magic Broom & Aerial Glide",
      "Swoop dynamically across the frame already in mid-flight on a magical broom, wings, or gliding device with pre-existing velocity.",
    ],
    [
      "A13",
      "Surfboard & Skate Slide",
      "Carve rapidly into the scene already riding a skateboard, hoverboard, or surfboard at high momentum.",
    ],
    [
      "A14",
      "Canopy Vine Swing",
      "Agile primate or acrobatic humanoid mascot with arms only: Swing into the frame suspended from an overhead vine or cable before releasing into a landing roll.",
      ["locomotion"],
    ],
    [
      "A15",
      "Pedal & Kart Dash",
      "Zoom across the frame already pedaling a mini bicycle or steering a colorful go-kart with full kinetic drive.",
    ],
    [
      "A16",
      "Parachute & Jetpack Descent",
      "Descend diagonally through the frame propelled by an already-deployed colorful parachute or mini jetpack thruster.",
    ],
    [
      "A17",
      "Acrobatic Tumbling Roll",
      "Burst into the frame mid-tumble with consecutive gymnastic flips or rolling momentum before springing upright.",
      ["locomotion"],
    ],
    [
      "A18",
      "Dino & Creature Mount",
      "Appear already in full kinetic motion riding atop a friendly dinosaur, safari mount, or fantasy creature galloping dynamically onto the stage with pre-existing velocity.",
    ],
    [
      "A19",
      "Plane & Aerial Glider",
      "Appear already swooping dynamically through the air piloting a colorful propeller aircraft, mini jet, or glider with pre-existing velocity.",
    ],
    [
      "A20",
      "Racecar & Cruiser Drive",
      "Appear already driving a vibrant roadster, racecar, or mini safari cruiser speeding enthusiastically onto the stage with high kinetic drive.",
    ],
    [
      "A21",
      "Parkour Sprint & Vault",
      "Appear already in an athletic parkour sprint, leaping and vaulting dynamically over stage obstacles with forward momentum before stabilizing.",
      ["locomotion"],
    ],
    [
      "A22",
      "Roller Skate Cruise",
      "Appear already gliding swiftly across the stage floor on colorful roller skates or inline blades, executing an agile spin before easing to a stop.",
      ["locomotion"],
    ],
    [
      "A23",
      "Springboard & Trampoline Bounce",
      "Launch into the scene with bouncy cartoon physics, rebounding off an off-screen trampoline or comic springboard into an athletic slide-stop.",
      ["locomotion"],
    ],
  ],
  intro_brand_interaction: [
    ["B01", "Mechanism Reveal", "Activate a simple mechanism that reveals the intact channel logo.", ["grasping"]],
    ["B02", "Light Activation", "Trigger a light pulse that reveals the intact channel logo."],
    ["B03", "Presenter Reveal", "Present the intact channel logo using a supported pose."],
    ["B04", "Surface Gleam", "Create a clean gleam across the intact channel logo."],
    ["B05", "Frame Assembly", "Assemble a decorative frame around the intact logo without reconstructing its letters."],
    ["B06", "Bubble Reveal", "Use a single bubble-like transition to reveal the intact channel logo."],
    ["B07", "Guided Logo Arrival", "Guide the intact channel logo into its hero position without touching signature features."],
    [
      "B08",
      "Particle Pop Reveal",
      "Trigger a colorful burst of stars, sparkles, or energy that pops the intact channel logo dynamically into center frame.",
    ],
    ["B09", "Hero Symmetrical Framing", "Frame the intact channel logo in an iconic hero composition with confident attitude."],
    [
      "B10",
      "Arcade Button Slam",
      "Smash a giant arcade button or pull a lever to trigger the channel logo popping dynamically into place.",
      ["grasping"],
    ],
    [
      "B11",
      "Logo Leap & Bounce",
      "Leap beside or interact with the channel logo as it lands bouncy and vibrant on the stage.",
      ["locomotion"],
    ],
    ["B12", "Magical Spark Sneeze", "Let out a cute tiny sneeze or breath that blooms into sparkling embers outlining the channel logo."],
  ],
  intro_performance_tone: [
    ["C01", "Energetic", "Perform with lively timing that remains compatible with the mascot's construction."],
    ["C02", "Playful", "Use a playful, friendly attitude without inventing anatomy or costume."],
    ["C03", "Thoughtful", "Use a curious, thoughtful attitude supported by pose and timing."],
    ["C04", "Warm", "Create a welcoming companion-like performance."],
    ["C05", "Confident", "Create a confident hero moment without adding permanent accessories."],
    ["C06", "Curious", "React with focused curiosity using supported expressions or body language."],
    ["C07", "Gently Comic", "Include one readable, safe comic recovery without excessive physical complexity."],
    [
      "C08",
      "Cartoon Comic Timing",
      "Use punchy animation physics, expressive comedic timing, and snappy reactions matching the mascot's style.",
    ],
    ["C09", "Hype Master", "Pump up the audience with high energy, confident bounce, and anticipation for the upcoming quiz."],
    [
      "C10",
      "Clever Detective",
      "Inspect the scene inquisitively, tilting head with an expressive eyebrow raise before smiling warmly at the viewer.",
    ],
  ],
  intro_verbal_hook: [
    ["D01", "Friendly Knowledge Challenge", "Challenge the viewers with upbeat confidence to test their brainpower on today's quiz topic."],
    ["D02", "Adventure Invitation", "Frame the quiz as a shared thrilling safari or quest across uncharted knowledge frontiers."],
    ["D03", "Brainpower Ignition", "Ignite viewer curiosity with an electric burst of enthusiasm, firing up their thinking engines for the challenge."],
    ["D04", "Warm Companion Welcome", "Welcome viewers with open-hearted friendship, celebrating curiosity and togetherness."],
    ["D05", "Curious Discovery Quest", "Invite viewers on an inquisitive journey to uncover hidden truths and surprising answers together."],
    ["D06", "Readiness Call", "Pump up audience focus and rally attention with a motivational call-to-arms."],
    ["D07", "Shared Playful Cheer", "Frame the quiz as joyful shared playtime with wholesome giggles and zero taunting."],
    ["D08", "Signature Action Call", "Deliver a snappy, high-impact signature call-to-action challenging viewers to think on their feet."],
    [
      "D09",
      "Challenger Hype",
      "Challenge the viewers directly with high energy to test their skills and aim for a flawless score.",
    ],
    [
      "D10",
      "Curiosity Spark",
      "Hook the viewers with an intriguing teaser about the challenge and sneaky surprises ahead.",
    ],
    ["D11", "Perfect Score Bet", "Lay down an exciting, friendly dare challenging viewers to achieve a flawless perfect 10/10 score."],
    ["D12", "Speed Reflex Dare", "Urge viewers to sharpen their lightning reflexes and think at maximum speed."],
    ["D13", "Brain Level-Up", "Challenge viewers to push beyond normal difficulty and unlock their maximum brainpower."],
    ["D14", "Trick Question Warning", "Alert viewers playfully that deceptive trick questions are hidden inside today's quiz."],
    ["D15", "Detective Code Crack", "Frame the quiz as a detective case where every question is an essential clue waiting to be solved."],
    ["D16", "Secret Clue Hunt", "Invite viewers to keep eagle eyes open for subtle hints and hidden easter eggs throughout the quiz."],
    ["D17", "Player One Start", "Trigger classic arcade game enthusiasm by announcing Player One has entered the arena."],
    ["D18", "Trivia Turbo Boost", "Ignite rocket-engine propulsion metaphors to launch into the quiz with supersonic velocity."],
    ["D19", "Power-Up Ignition", "Collect an imaginary brainpower buff or power-up crystal to supercharge thinking skills."],
    ["D20", "Boss Battle Intro", "Frame today's quiz round as a climactic showdown against a formidable puzzle boss."],
    ["D21", "High-Score Quest", "Motivate competitive viewers to set an all-time record and climb to the top of the leaderboard."],
    ["D22", "Grand Arena Showtime", "Channel the charismatic energy of a prime-time television host welcoming a massive arena audience."],
    ["D23", "Synapse Sparks Cheer", "Electrify the atmosphere with infectious enthusiasm, celebrating the joy of clever thinking."],
    ["D24", "Pop Quiz Surprise", "Pretend to be comically surprised by a sudden quiz alarm before embracing the excitement."],
    ["D25", "Playful Snack Bet", "Wager an absurd imaginary prize like a cookie or favorite snack that viewers will stumble."],
    ["D26", "Mascot Rivalry Taunt", "Playfully question whether viewers can outsmart the channel's mascot in a good-natured battle of wits."],
    ["D27", "Brain Freeze Alert", "Humorously warn viewers to prepare their thinking caps before their brain melts from intense questions."],
    ["D28", "Expedition Launch", "Blow the departure whistle for a knowledge expedition into strange and wonderful trivia realms."],
    ["D29", "Cosmic Brain Odyssey", "Blast off into an interplanetary voyage of curiosity across galaxies of fascinating facts."],
    ["D30", "Treasure Mind Quest", "Depict the quiz as uncovering a hidden treasure chest where every correct answer is a gold coin."],
  ],
  intro_environment: [
    [
      "I01",
      "Neon Cyber Arcade",
      "Set upon a sleek black mirror-gloss acrylic floor with glowing cyan and magenta neon grid lines, framed by illuminated arcade portal arches and distant floating holographic particle dust.",
    ],
    [
      "I02",
      "Grand Trivia Arena",
      "Set inside a prestigious prime-time television gameshow arena featuring polished reflective hardwood floors, tiered cobalt cyclorama walls, volumetric overhead spotlights, and golden buzzer pedestals.",
    ],
    [
      "I03",
      "Playful Candy Toyland",
      "Set in a whimsical 3D confectionary wonderland with pastel marshmallow flooring, towering peppermint spiral pillars, soft warm studio lighting, and sparkling powdered sugar particle drift.",
    ],
    [
      "I04",
      "Cosmic Galaxy Planetarium",
      "Set on a suspended glass observation deck looking down into deep space, surrounded by glowing orbital rings, deep violet-amber nebula washes, and twinkling starlight bokeh.",
    ],
    [
      "I05",
      "Enchanted Magic Forest",
      "Set upon an illuminated petal dais surrounded by bioluminescent mossy platforms, golden volumetric sunlight shafts filtering through ancient canopy vines, and floating firefly sparkles.",
    ],
    [
      "I06",
      "Pop-Art Comic Studio",
      "Set in an energetic comic pop-art studio with high-contrast checkered glossy tiles, playful 3D geometric polyhedrons, vibrant saturated key lighting, and crisp halftone accent trims.",
    ],
    [
      "I07",
      "High-Tech Futuristic Lab",
      "Set in a minimalist sci-fi laboratory with brushed titanium floors inset with glowing cyan fiber-optic tracks, floating 3D holographic interface screens, and clean clinical rim lighting.",
    ],
    [
      "I08",
      "Golden Sunset Amphitheater",
      "Set on a sun-drenched outdoor classical marble stage bathed in warm golden-hour rim lighting, framed by elegant architectural pillars, soft long shadows, and shimmering amber air.",
    ],
  ],
};

const INTRO_MEDIUM_COMPLEXITY_IDS = new Set([
  "A04", "A05", "A08", "A09", "A10", "A12", "A13", "A14", "A15", "A16", "A17",
  "A18", "A19", "A20", "A21", "A22", "A23",
  "B01", "B05", "B10", "B11",
  "C07", "C08", "C09",
  "I01", "I02", "I03", "I04", "I05", "I06", "I07", "I08",
]);

export const INTRO_SEEDS: CreativeSeed[] = buildSeedsFromDefinitions(
  INTRO_SEED_DEFINITIONS,
  "intro",
  INTRO_MEDIUM_COMPLEXITY_IDS,
);
