import type { TargetCountryOption, TargetLanguageOption } from "./types.js";

export const TARGET_LANGUAGE_OPTIONS: TargetLanguageOption[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
];

export const TARGET_COUNTRY_OPTIONS: TargetCountryOption[] = [
  {
    rank: 0,
    code: "VN",
    name: "Việt Nam (Vietnam)",
    nameVi: "Việt Nam",
    nameEn: "Vietnam",
    flag: "🇻🇳",
    defaultLanguage: "Vietnamese",
    languageNameVi: "Tiếng Việt",
  },
  {
    rank: 1,
    code: "AU",
    name: "Úc (Australia)",
    nameVi: "Úc",
    nameEn: "Australia",
    flag: "🇦🇺",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 2,
    code: "US",
    name: "Hoa Kỳ (USA)",
    nameVi: "Hoa Kỳ",
    nameEn: "United States",
    flag: "🇺🇸",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 3,
    code: "CA",
    name: "Canada",
    nameVi: "Canada",
    nameEn: "Canada",
    flag: "🇨🇦",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 4,
    code: "NZ",
    name: "New Zealand",
    nameVi: "New Zealand",
    nameEn: "New Zealand",
    flag: "🇳🇿",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 5,
    code: "CH",
    name: "Thụy Sĩ (Switzerland)",
    nameVi: "Thụy Sĩ",
    nameEn: "Switzerland",
    flag: "🇨🇭",
    defaultLanguage: "German",
    languageNameVi: "Tiếng Đức",
  },
  {
    rank: 6,
    code: "GB",
    name: "Vương quốc Anh (UK)",
    nameVi: "Vương quốc Anh",
    nameEn: "United Kingdom",
    flag: "🇬🇧",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 7,
    code: "NO",
    name: "Na Uy (Norway)",
    nameVi: "Na Uy",
    nameEn: "Norway",
    flag: "🇳🇴",
    defaultLanguage: "Norwegian",
    languageNameVi: "Tiếng Na Uy",
  },
  {
    rank: 8,
    code: "DE",
    name: "Đức (Germany)",
    nameVi: "Đức",
    nameEn: "Germany",
    flag: "🇩🇪",
    defaultLanguage: "German",
    languageNameVi: "Tiếng Đức",
  },
  {
    rank: 9,
    code: "IE",
    name: "Ireland",
    nameVi: "Ireland",
    nameEn: "Ireland",
    flag: "🇮🇪",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 10,
    code: "NL",
    name: "Hà Lan (Netherlands)",
    nameVi: "Hà Lan",
    nameEn: "Netherlands",
    flag: "🇳🇱",
    defaultLanguage: "Dutch",
    languageNameVi: "Tiếng Hà Lan",
  },
  {
    rank: 11,
    code: "DK",
    name: "Đan Mạch (Denmark)",
    nameVi: "Đan Mạch",
    nameEn: "Denmark",
    flag: "🇩🇰",
    defaultLanguage: "Danish",
    languageNameVi: "Tiếng Đan Mạch",
  },
  {
    rank: 12,
    code: "SE",
    name: "Thụy Điển (Sweden)",
    nameVi: "Thụy Điển",
    nameEn: "Sweden",
    flag: "🇸🇪",
    defaultLanguage: "Swedish",
    languageNameVi: "Tiếng Thụy Điển",
  },
  {
    rank: 13,
    code: "AT",
    name: "Áo (Austria)",
    nameVi: "Áo",
    nameEn: "Austria",
    flag: "🇦🇹",
    defaultLanguage: "German",
    languageNameVi: "Tiếng Đức",
  },
  {
    rank: 14,
    code: "FI",
    name: "Phần Lan (Finland)",
    nameVi: "Phần Lan",
    nameEn: "Finland",
    flag: "🇫🇮",
    defaultLanguage: "Finnish",
    languageNameVi: "Tiếng Phần Lan",
  },
  {
    rank: 15,
    code: "BE",
    name: "Bỉ (Belgium)",
    nameVi: "Bỉ",
    nameEn: "Belgium",
    flag: "🇧🇪",
    defaultLanguage: "Dutch",
    languageNameVi: "Tiếng Hà Lan",
  },
  {
    rank: 16,
    code: "FR",
    name: "Pháp (France)",
    nameVi: "Pháp",
    nameEn: "France",
    flag: "🇫🇷",
    defaultLanguage: "French",
    languageNameVi: "Tiếng Pháp",
  },
  {
    rank: 17,
    code: "SG",
    name: "Singapore",
    nameVi: "Singapore",
    nameEn: "Singapore",
    flag: "🇸🇬",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 18,
    code: "KR",
    name: "Hàn Quốc (South Korea)",
    nameVi: "Hàn Quốc",
    nameEn: "South Korea",
    flag: "🇰🇷",
    defaultLanguage: "Korean",
    languageNameVi: "Tiếng Hàn",
  },
  {
    rank: 19,
    code: "JP",
    name: "Nhật Bản (Japan)",
    nameVi: "Nhật Bản",
    nameEn: "Japan",
    flag: "🇯🇵",
    defaultLanguage: "Japanese",
    languageNameVi: "Tiếng Nhật",
  },
  {
    rank: 20,
    code: "AE",
    name: "UAE (United Arab Emirates)",
    nameVi: "UAE",
    nameEn: "United Arab Emirates",
    flag: "🇦🇪",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
];

export const PREFERRED_LANGUAGE_FLAGS: Record<string, string> = {
  English: "🇺🇸",
  German: "🇩🇪",
  Dutch: "🇳🇱",
  French: "🇫🇷",
  Japanese: "🇯🇵",
  Korean: "🇰🇷",
  Norwegian: "🇳🇴",
  Danish: "🇩🇰",
  Swedish: "🇸🇪",
  Finnish: "🇫🇮",
};

export const PREFERRED_LANGUAGE_COUNTRIES: Record<string, string> = {
  English: "US",
  German: "DE",
  Dutch: "NL",
  French: "FR",
  Japanese: "JP",
  Korean: "KR",
  Norwegian: "NO",
  Danish: "DK",
  Swedish: "SE",
  Finnish: "FI",
};
