import type { TargetCountryOption, TargetLanguageOption } from "./types.js";

export const TARGET_LANGUAGE_OPTIONS: TargetLanguageOption[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
];

export const TARGET_COUNTRY_OPTIONS: TargetCountryOption[] = [
  {
    rank: 1,
    code: "US",
    name: "United States (USA)",
    nameVi: "United States",
    nameEn: "United States",
    flag: "🇺🇸",
    defaultLanguage: "English",
    languageNameVi: "English",
  },
  {
    rank: 2,
    code: "AU",
    name: "Australia",
    nameVi: "Australia",
    nameEn: "Australia",
    flag: "🇦🇺",
    defaultLanguage: "English",
    languageNameVi: "English",
  },
  {
    rank: 3,
    code: "CA",
    name: "Canada",
    nameVi: "Canada",
    nameEn: "Canada",
    flag: "🇨🇦",
    defaultLanguage: "English",
    languageNameVi: "English",
  },
  {
    rank: 4,
    code: "NZ",
    name: "New Zealand",
    nameVi: "New Zealand",
    nameEn: "New Zealand",
    flag: "🇳🇿",
    defaultLanguage: "English",
    languageNameVi: "English",
  },
  {
    rank: 5,
    code: "CH",
    name: "Switzerland",
    nameVi: "Switzerland",
    nameEn: "Switzerland",
    flag: "🇨🇭",
    defaultLanguage: "German",
    languageNameVi: "German",
  },
  {
    rank: 6,
    code: "GB",
    name: "United Kingdom (UK)",
    nameVi: "United Kingdom",
    nameEn: "United Kingdom",
    flag: "🇬🇧",
    defaultLanguage: "English",
    languageNameVi: "English",
  },
  {
    rank: 7,
    code: "NO",
    name: "Norway",
    nameVi: "Norway",
    nameEn: "Norway",
    flag: "🇳🇴",
    defaultLanguage: "Norwegian",
    languageNameVi: "Norwegian",
  },
  {
    rank: 8,
    code: "DE",
    name: "Germany",
    nameVi: "Germany",
    nameEn: "Germany",
    flag: "🇩🇪",
    defaultLanguage: "German",
    languageNameVi: "German",
  },
  {
    rank: 9,
    code: "IE",
    name: "Ireland",
    nameVi: "Ireland",
    nameEn: "Ireland",
    flag: "🇮🇪",
    defaultLanguage: "English",
    languageNameVi: "English",
  },
  {
    rank: 10,
    code: "NL",
    name: "Netherlands",
    nameVi: "Netherlands",
    nameEn: "Netherlands",
    flag: "🇳🇱",
    defaultLanguage: "Dutch",
    languageNameVi: "Dutch",
  },
  {
    rank: 11,
    code: "DK",
    name: "Denmark",
    nameVi: "Denmark",
    nameEn: "Denmark",
    flag: "🇩🇰",
    defaultLanguage: "Danish",
    languageNameVi: "Danish",
  },
  {
    rank: 12,
    code: "SE",
    name: "Sweden",
    nameVi: "Sweden",
    nameEn: "Sweden",
    flag: "🇸🇪",
    defaultLanguage: "Swedish",
    languageNameVi: "Swedish",
  },
  {
    rank: 13,
    code: "AT",
    name: "Austria",
    nameVi: "Austria",
    nameEn: "Austria",
    flag: "🇦🇹",
    defaultLanguage: "German",
    languageNameVi: "German",
  },
  {
    rank: 14,
    code: "FI",
    name: "Finland",
    nameVi: "Finland",
    nameEn: "Finland",
    flag: "🇫🇮",
    defaultLanguage: "Finnish",
    languageNameVi: "Finnish",
  },
  {
    rank: 15,
    code: "BE",
    name: "Belgium",
    nameVi: "Belgium",
    nameEn: "Belgium",
    flag: "🇧🇪",
    defaultLanguage: "Dutch",
    languageNameVi: "Dutch",
  },
  {
    rank: 16,
    code: "FR",
    name: "France",
    nameVi: "France",
    nameEn: "France",
    flag: "🇫🇷",
    defaultLanguage: "French",
    languageNameVi: "French",
  },
  {
    rank: 17,
    code: "SG",
    name: "Singapore",
    nameVi: "Singapore",
    nameEn: "Singapore",
    flag: "🇸🇬",
    defaultLanguage: "English",
    languageNameVi: "English",
  },
  {
    rank: 18,
    code: "KR",
    name: "South Korea",
    nameVi: "South Korea",
    nameEn: "South Korea",
    flag: "🇰🇷",
    defaultLanguage: "Korean",
    languageNameVi: "Korean",
  },
  {
    rank: 19,
    code: "JP",
    name: "Japan",
    nameVi: "Japan",
    nameEn: "Japan",
    flag: "🇯🇵",
    defaultLanguage: "Japanese",
    languageNameVi: "Japanese",
  },
  {
    rank: 20,
    code: "AE",
    name: "United Arab Emirates (UAE)",
    nameVi: "United Arab Emirates",
    nameEn: "United Arab Emirates",
    flag: "🇦🇪",
    defaultLanguage: "English",
    languageNameVi: "English",
  },
];

export const PREFERRED_LANGUAGE_FLAGS: Record<string, string> = {
  English: "🇺🇸",
  German: "🇩🇪",
  Dutch: "🇳🇱",
  French: "🇫🇷",
  Japanese: "🇯🇵",
  Korean: "🇰🇷",
  Norwegian: "🇳🇴",
  Danish: "🇩🇰",
  Swedish: "🇸🇪",
  Finnish: "🇫🇮",
};

export const PREFERRED_LANGUAGE_COUNTRIES: Record<string, string> = {
  English: "US",
  German: "DE",
  Dutch: "NL",
  French: "FR",
  Japanese: "JP",
  Korean: "KR",
  Norwegian: "NO",
  Danish: "DK",
  Swedish: "SE",
  Finnish: "FI",
};
