import type { TargetCountryOption, TargetLanguageOption } from "./types.js";

export const TARGET_LANGUAGE_OPTIONS: TargetLanguageOption[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "tl", name: "Tagalog", nativeName: "Filipino" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
];

export const TARGET_COUNTRY_OPTIONS: TargetCountryOption[] = [
  {
    rank: 1,
    code: "AU",
    name: "Úc (Australia)",
    nameVi: "Úc",
    nameEn: "Australia",
    flag: "🇦🇺",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 2,
    code: "US",
    name: "Hoa Kỳ (USA)",
    nameVi: "Hoa Kỳ",
    nameEn: "United States",
    flag: "🇺🇸",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 3,
    code: "CA",
    name: "Canada",
    nameVi: "Canada",
    nameEn: "Canada",
    flag: "🇨🇦",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 4,
    code: "NZ",
    name: "New Zealand",
    nameVi: "New Zealand",
    nameEn: "New Zealand",
    flag: "🇳🇿",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 5,
    code: "CH",
    name: "Thụy Sĩ (Switzerland)",
    nameVi: "Thụy Sĩ",
    nameEn: "Switzerland",
    flag: "🇨🇭",
    defaultLanguage: "German",
    languageNameVi: "Tiếng Đức",
  },
  {
    rank: 6,
    code: "GB",
    name: "Vương quốc Anh (UK)",
    nameVi: "Vương quốc Anh",
    nameEn: "United Kingdom",
    flag: "🇬🇧",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 7,
    code: "NO",
    name: "Na Uy (Norway)",
    nameVi: "Na Uy",
    nameEn: "Norway",
    flag: "🇳🇴",
    defaultLanguage: "Norwegian",
    languageNameVi: "Tiếng Na Uy",
  },
  {
    rank: 8,
    code: "DE",
    name: "Đức (Germany)",
    nameVi: "Đức",
    nameEn: "Germany",
    flag: "🇩🇪",
    defaultLanguage: "German",
    languageNameVi: "Tiếng Đức",
  },
  {
    rank: 9,
    code: "IE",
    name: "Ireland",
    nameVi: "Ireland",
    nameEn: "Ireland",
    flag: "🇮🇪",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 10,
    code: "NL",
    name: "Hà Lan (Netherlands)",
    nameVi: "Hà Lan",
    nameEn: "Netherlands",
    flag: "🇳🇱",
    defaultLanguage: "Dutch",
    languageNameVi: "Tiếng Hà Lan",
  },
  {
    rank: 11,
    code: "DK",
    name: "Đan Mạch (Denmark)",
    nameVi: "Đan Mạch",
    nameEn: "Denmark",
    flag: "🇩🇰",
    defaultLanguage: "Danish",
    languageNameVi: "Tiếng Đan Mạch",
  },
  {
    rank: 12,
    code: "SE",
    name: "Thụy Điển (Sweden)",
    nameVi: "Thụy Điển",
    nameEn: "Sweden",
    flag: "🇸🇪",
    defaultLanguage: "Swedish",
    languageNameVi: "Tiếng Thụy Điển",
  },
  {
    rank: 13,
    code: "FI",
    name: "Phần Lan (Finland)",
    nameVi: "Phần Lan",
    nameEn: "Finland",
    flag: "🇫🇮",
    defaultLanguage: "Finnish",
    languageNameVi: "Tiếng Phần Lan",
  },
  {
    rank: 14,
    code: "AT",
    name: "Áo (Austria)",
    nameVi: "Áo",
    nameEn: "Austria",
    flag: "🇦🇹",
    defaultLanguage: "German",
    languageNameVi: "Tiếng Đức",
  },
  {
    rank: 15,
    code: "BE",
    name: "Bỉ (Belgium)",
    nameVi: "Bỉ",
    nameEn: "Belgium",
    flag: "🇧🇪",
    defaultLanguage: "Dutch",
    languageNameVi: "Tiếng Hà Lan",
  },
  {
    rank: 16,
    code: "FR",
    name: "Pháp (France)",
    nameVi: "Pháp",
    nameEn: "France",
    flag: "🇫🇷",
    defaultLanguage: "French",
    languageNameVi: "Tiếng Pháp",
  },
  {
    rank: 17,
    code: "KR",
    name: "Hàn Quốc (South Korea)",
    nameVi: "Hàn Quốc",
    nameEn: "South Korea",
    flag: "🇰🇷",
    defaultLanguage: "Korean",
    languageNameVi: "Tiếng Hàn",
  },
  {
    rank: 18,
    code: "JP",
    name: "Nhật Bản (Japan)",
    nameVi: "Nhật Bản",
    nameEn: "Japan",
    flag: "🇯🇵",
    defaultLanguage: "Japanese",
    languageNameVi: "Tiếng Nhật",
  },
  {
    rank: 19,
    code: "SG",
    name: "Singapore",
    nameVi: "Singapore",
    nameEn: "Singapore",
    flag: "🇸🇬",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 20,
    code: "VN",
    name: "Việt Nam (Vietnam)",
    nameVi: "Việt Nam",
    nameEn: "Vietnam",
    flag: "🇻🇳",
    defaultLanguage: "Vietnamese",
    languageNameVi: "Tiếng Việt",
  },
  {
    rank: 21,
    code: "ES",
    name: "Tây Ban Nha (Spain)",
    nameVi: "Tây Ban Nha",
    nameEn: "Spain",
    flag: "🇪🇸",
    defaultLanguage: "Spanish",
    languageNameVi: "Tiếng Tây Ban Nha",
  },
  {
    rank: 22,
    code: "IT",
    name: "Ý (Italy)",
    nameVi: "Ý",
    nameEn: "Italy",
    flag: "🇮🇹",
    defaultLanguage: "Italian",
    languageNameVi: "Tiếng Ý",
  },
  {
    rank: 23,
    code: "BR",
    name: "Brazil",
    nameVi: "Brazil",
    nameEn: "Brazil",
    flag: "🇧🇷",
    defaultLanguage: "Portuguese",
    languageNameVi: "Tiếng Bồ Đào Nha",
  },
  {
    rank: 24,
    code: "MX",
    name: "Mexico",
    nameVi: "Mexico",
    nameEn: "Mexico",
    flag: "🇲🇽",
    defaultLanguage: "Spanish",
    languageNameVi: "Tiếng Tây Ban Nha",
  },
  {
    rank: 25,
    code: "ID",
    name: "Indonesia",
    nameVi: "Indonesia",
    nameEn: "Indonesia",
    flag: "🇮🇩",
    defaultLanguage: "Indonesian",
    languageNameVi: "Tiếng Indonesia",
  },
  {
    rank: 26,
    code: "IN",
    name: "Ấn Độ (India)",
    nameVi: "Ấn Độ",
    nameEn: "India",
    flag: "🇮🇳",
    defaultLanguage: "Hindi",
    languageNameVi: "Tiếng Hindi",
  },
  {
    rank: 27,
    code: "PH",
    name: "Philippines",
    nameVi: "Philippines",
    nameEn: "Philippines",
    flag: "🇵🇭",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 28,
    code: "TH",
    name: "Thái Lan (Thailand)",
    nameVi: "Thái Lan",
    nameEn: "Thailand",
    flag: "🇹🇭",
    defaultLanguage: "Thai",
    languageNameVi: "Tiếng Thái",
  },
  {
    rank: 29,
    code: "MY",
    name: "Malaysia",
    nameVi: "Malaysia",
    nameEn: "Malaysia",
    flag: "🇲🇾",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 30,
    code: "TW",
    name: "Đài Loan (Taiwan)",
    nameVi: "Đài Loan",
    nameEn: "Taiwan",
    flag: "🇹🇼",
    defaultLanguage: "Chinese",
    languageNameVi: "Tiếng Trung",
  },
  {
    rank: 31,
    code: "HK",
    name: "Hồng Kông (Hong Kong)",
    nameVi: "Hồng Kông",
    nameEn: "Hong Kong",
    flag: "🇭🇰",
    defaultLanguage: "Chinese",
    languageNameVi: "Tiếng Trung",
  },
  {
    rank: 32,
    code: "AE",
    name: "UAE (United Arab Emirates)",
    nameVi: "UAE",
    nameEn: "United Arab Emirates",
    flag: "🇦🇪",
    defaultLanguage: "Arabic",
    languageNameVi: "Tiếng Ả Rập",
  },
  {
    rank: 33,
    code: "SA",
    name: "Ả Rập Xê Út (Saudi Arabia)",
    nameVi: "Ả Rập Xê Út",
    nameEn: "Saudi Arabia",
    flag: "🇸🇦",
    defaultLanguage: "Arabic",
    languageNameVi: "Tiếng Ả Rập",
  },
  {
    rank: 34,
    code: "PL",
    name: "Ba Lan (Poland)",
    nameVi: "Ba Lan",
    nameEn: "Poland",
    flag: "🇵🇱",
    defaultLanguage: "Polish",
    languageNameVi: "Tiếng Ba Lan",
  },
  {
    rank: 35,
    code: "TR",
    name: "Thổ Nhĩ Kỳ (Turkey)",
    nameVi: "Thổ Nhĩ Kỳ",
    nameEn: "Turkey",
    flag: "🇹🇷",
    defaultLanguage: "Turkish",
    languageNameVi: "Tiếng Thổ Nhĩ Kỳ",
  },
  {
    rank: 36,
    code: "ZA",
    name: "Nam Phi (South Africa)",
    nameVi: "Nam Phi",
    nameEn: "South Africa",
    flag: "🇿🇦",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 37,
    code: "PT",
    name: "Bồ Đào Nha (Portugal)",
    nameVi: "Bồ Đào Nha",
    nameEn: "Portugal",
    flag: "🇵🇹",
    defaultLanguage: "Portuguese",
    languageNameVi: "Tiếng Bồ Đào Nha",
  },
  {
    rank: 38,
    code: "GR",
    name: "Hy Lạp (Greece)",
    nameVi: "Hy Lạp",
    nameEn: "Greece",
    flag: "🇬🇷",
    defaultLanguage: "Greek",
    languageNameVi: "Tiếng Hy Lạp",
  },
  {
    rank: 39,
    code: "CZ",
    name: "Séc (Czech Republic)",
    nameVi: "Séc",
    nameEn: "Czech Republic",
    flag: "🇨🇿",
    defaultLanguage: "Czech",
    languageNameVi: "Tiếng Séc",
  },
  {
    rank: 40,
    code: "RO",
    name: "Romania",
    nameVi: "Romania",
    nameEn: "Romania",
    flag: "🇷🇴",
    defaultLanguage: "Romanian",
    languageNameVi: "Tiếng Romania",
  },
  {
    rank: 41,
    code: "HU",
    name: "Hungary",
    nameVi: "Hungary",
    nameEn: "Hungary",
    flag: "🇭🇺",
    defaultLanguage: "Hungarian",
    languageNameVi: "Tiếng Hungary",
  },
  {
    rank: 42,
    code: "IL",
    name: "Israel",
    nameVi: "Israel",
    nameEn: "Israel",
    flag: "🇮🇱",
    defaultLanguage: "Hebrew",
    languageNameVi: "Tiếng Do Thái",
  },
  {
    rank: 43,
    code: "CL",
    name: "Chile",
    nameVi: "Chile",
    nameEn: "Chile",
    flag: "🇨🇱",
    defaultLanguage: "Spanish",
    languageNameVi: "Tiếng Tây Ban Nha",
  },
  {
    rank: 44,
    code: "CO",
    name: "Colombia",
    nameVi: "Colombia",
    nameEn: "Colombia",
    flag: "🇨🇴",
    defaultLanguage: "Spanish",
    languageNameVi: "Tiếng Tây Ban Nha",
  },
  {
    rank: 45,
    code: "AR",
    name: "Argentina",
    nameVi: "Argentina",
    nameEn: "Argentina",
    flag: "🇦🇷",
    defaultLanguage: "Spanish",
    languageNameVi: "Tiếng Tây Ban Nha",
  },
  {
    rank: 46,
    code: "EG",
    name: "Ai Cập (Egypt)",
    nameVi: "Ai Cập",
    nameEn: "Egypt",
    flag: "🇪🇬",
    defaultLanguage: "Arabic",
    languageNameVi: "Tiếng Ả Rập",
  },
  {
    rank: 47,
    code: "NG",
    name: "Nigeria",
    nameVi: "Nigeria",
    nameEn: "Nigeria",
    flag: "🇳🇬",
    defaultLanguage: "English",
    languageNameVi: "Tiếng Anh",
  },
  {
    rank: 48,
    code: "PK",
    name: "Pakistan",
    nameVi: "Pakistan",
    nameEn: "Pakistan",
    flag: "🇵🇰",
    defaultLanguage: "Urdu",
    languageNameVi: "Tiếng Urdu",
  },
  {
    rank: 49,
    code: "BD",
    name: "Bangladesh",
    nameVi: "Bangladesh",
    nameEn: "Bangladesh",
    flag: "🇧🇩",
    defaultLanguage: "Bengali",
    languageNameVi: "Tiếng Bengali",
  },
  {
    rank: 50,
    code: "RU",
    name: "Nga (Russia)",
    nameVi: "Nga",
    nameEn: "Russia",
    flag: "🇷🇺",
    defaultLanguage: "Russian",
    languageNameVi: "Tiếng Nga",
  },
];

export const PREFERRED_LANGUAGE_FLAGS: Record<string, string> = {
  English: "🇺🇸",
  German: "🇩🇪",
  Dutch: "🇳🇱",
  French: "🇫🇷",
  Japanese: "🇯🇵",
  Korean: "🇰🇷",
  Norwegian: "🇳🇴",
  Danish: "🇩🇰",
  Swedish: "🇸🇪",
  Finnish: "🇫🇮",
};

export const PREFERRED_LANGUAGE_COUNTRIES: Record<string, string> = {
  English: "US",
  German: "DE",
  Dutch: "NL",
  French: "FR",
  Japanese: "JP",
  Korean: "KR",
  Norwegian: "NO",
  Danish: "DK",
  Swedish: "SE",
  Finnish: "FI",
};
