import type { MascotAnimationRecipe } from "./animationTypes.js";

export const THINKING_RECIPES: readonly MascotAnimationRecipe[] = [
  {
    id: "thinking-01-head-tilt-left",
    state: "thinking",
    slot_index: 1,
    name: "Head Tilt Left",
    description: "Gentle curiosity tilt to the left while pondering with soft eyes",
    action_instruction:
      "Character remains centered and tilts head gently 15 degrees to the left, pausing thoughtfully before returning to center",
    energy_level: "low",
    loop_policy: "loop",
    movement_intent: "calm thoughtful contemplation",
  },
  {
    id: "thinking-02-head-tilt-right",
    state: "thinking",
    slot_index: 2,
    name: "Head Tilt Right",
    description: "Subtle curious head tilt to the right with focused expression",
    action_instruction:
      "Character remains centered and tilts head gently 15 degrees to the right, looking slightly upward then easing back",
    energy_level: "low",
    loop_policy: "loop",
    movement_intent: "calm thoughtful contemplation",
  },
  {
    id: "thinking-03-look-up",
    state: "thinking",
    slot_index: 3,
    name: "Look Up",
    description: "Gazing upward thoughtfully as if searching for an answer",
    action_instruction:
      "Character lifts eyes and tilts chin slightly upward in thoughtful reflection, then smoothly lowers back to front gaze",
    energy_level: "low",
    loop_policy: "loop",
    movement_intent: "calm reflective search",
  },
  {
    id: "thinking-04-look-down",
    state: "thinking",
    slot_index: 4,
    name: "Look Down",
    description: "Deep concentration looking downward at problem details",
    action_instruction: "Character lowers eyes and chin slightly in focused study, contemplating the problem, then gently raises gaze back",
    energy_level: "low",
    loop_policy: "loop",
    movement_intent: "deep focused study",
  },
  {
    id: "thinking-05-paw-near-chin",
    state: "thinking",
    slot_index: 5,
    name: "Paw Near Chin",
    description: "Hand or paw brought lightly toward chin in classic thinking posture",
    action_instruction: "Character raises one hand or paw toward chin in classic thinker pose, taps chin softly, and relaxes arm slightly",
    energy_level: "low",
    loop_policy: "loop",
    movement_intent: "classic contemplative gesture",
  },
  {
    id: "thinking-06-gentle-sway",
    state: "thinking",
    slot_index: 6,
    name: "Gentle Sway",
    description: "Subtle rhythmic body sway while deliberating",
    action_instruction: "Character sways body gently left and right with minimal torso displacement, maintaining calm centered balance",
    energy_level: "low",
    loop_policy: "loop",
    movement_intent: "rhythmic contemplative poise",
  },
  {
    id: "thinking-07-focused-blink",
    state: "thinking",
    slot_index: 7,
    name: "Focused Blink",
    description: "Intent focus with deliberate calm double-blink",
    action_instruction: "Character blinks thoughtfully and slowly with intelligent eyes, furrowing brow slightly in contemplation",
    energy_level: "low",
    loop_policy: "loop",
    movement_intent: "acute focused awareness",
  },
  {
    id: "thinking-08-curious-lean-left",
    state: "thinking",
    slot_index: 8,
    name: "Curious Lean Left",
    description: "Inquisitive slight lean to the left examining a puzzle",
    action_instruction: "Character leans upper body slightly toward the left with curious eyes, inspecting details before returning center",
    energy_level: "low",
    loop_policy: "loop",
    movement_intent: "inquisitive observation",
  },
  {
    id: "thinking-09-curious-lean-right",
    state: "thinking",
    slot_index: 9,
    name: "Curious Lean Right",
    description: "Inquisitive slight lean to the right examining options",
    action_instruction: "Character leans upper body slightly toward the right with interested expression, easing smoothly back to neutral",
    energy_level: "low",
    loop_policy: "loop",
    movement_intent: "inquisitive observation",
  },
  {
    id: "thinking-10-calm-breathing",
    state: "thinking",
    slot_index: 10,
    name: "Calm Breathing",
    description: "Serene rhythmic breathing and settled concentration",
    action_instruction: "Character performs subtle inhale and chest rise followed by gentle exhale, maintaining serene focused posture",
    energy_level: "low",
    loop_policy: "loop",
    movement_intent: "peaceful grounded focus",
  },
];

export const CELEBRATE_RECIPES: readonly MascotAnimationRecipe[] = [
  {
    id: "celebrate-01-both-hands-up",
    state: "celebrate",
    slot_index: 1,
    name: "Both Hands Up",
    description: "Triumphant raising of both hands in victory celebration",
    action_instruction: "Character joyfully raises both arms high overhead with wide beaming smile, cheering before settling to happy rest",
    energy_level: "high",
    loop_policy: "one_shot_rest",
    movement_intent: "triumphant victory cheer",
  },
  {
    id: "celebrate-02-small-jump",
    state: "celebrate",
    slot_index: 2,
    name: "Small Jump",
    description: "Cute cheerful hop with arms outstretched",
    action_instruction:
      "Character performs a small excited hop, lifting feet briefly off ground with joyful expression, landing gracefully",
    energy_level: "high",
    loop_policy: "one_shot_rest",
    movement_intent: "exuberant playful bounce",
  },
  {
    id: "celebrate-03-clap",
    state: "celebrate",
    slot_index: 3,
    name: "Clap",
    description: "Enthusiastic clapping with bright cheerful smile",
    action_instruction: "Character brings hands together in happy rhythmic claps with sparkling eyes, ending in delighted applause",
    energy_level: "moderate",
    loop_policy: "one_shot_rest",
    movement_intent: "delighted audience applause",
  },
  {
    id: "celebrate-04-lean-left-smile",
    state: "celebrate",
    slot_index: 4,
    name: "Lean Left Smile",
    description: "Playful lean to the left flashing a proud grin",
    action_instruction: "Character leans playfully to the left with bright radiant smile and cheerful wink, then eases back to rest",
    energy_level: "moderate",
    loop_policy: "one_shot_rest",
    movement_intent: "playful proud cheer",
  },
  {
    id: "celebrate-05-lean-right-smile",
    state: "celebrate",
    slot_index: 5,
    name: "Lean Right Smile",
    description: "Playful lean to the right flashing a proud grin",
    action_instruction: "Character leans playfully to the right with happy beaming smile and jaunty tilt, easing back to centered rest",
    energy_level: "moderate",
    loop_policy: "one_shot_rest",
    movement_intent: "playful proud cheer",
  },
  {
    id: "celebrate-06-excited-bounce",
    state: "celebrate",
    slot_index: 6,
    name: "Excited Bounce",
    description: "Energetic knee bend and springy celebration bounce",
    action_instruction: "Character crouches slightly and springs upward in a double excited bounce with arms waving happily",
    energy_level: "high",
    loop_policy: "one_shot_rest",
    movement_intent: "high-energy buoyant celebration",
  },
  {
    id: "celebrate-07-one-hand-victory",
    state: "celebrate",
    slot_index: 7,
    name: "One Hand Victory",
    description: "Single fist pump or paw raised in proud success",
    action_instruction: "Character pumps one fist or paw triumphantly into the air with confident proud smile and victorious stance",
    energy_level: "high",
    loop_policy: "one_shot_rest",
    movement_intent: "victorious champion fist pump",
  },
  {
    id: "celebrate-08-joyful-wave",
    state: "celebrate",
    slot_index: 8,
    name: "Joyful Wave",
    description: "Friendly energetic two-handed or cheerful wave to the viewer",
    action_instruction: "Character waves enthusiastically with broad happy smile, acknowledging success and sharing joy with user",
    energy_level: "moderate",
    loop_policy: "one_shot_rest",
    movement_intent: "warm shared victory greeting",
  },
  {
    id: "celebrate-09-excited-turn",
    state: "celebrate",
    slot_index: 9,
    name: "Excited Turn",
    description: "Quick celebratory half-spin or pirouette and pose",
    action_instruction: "Character swivels body in a brisk joyful spin, returning to front with proud open pose and happy grin",
    energy_level: "high",
    loop_policy: "one_shot_rest",
    movement_intent: "spirited celebratory spin",
  },
  {
    id: "celebrate-10-happy-bow",
    state: "celebrate",
    slot_index: 10,
    name: "Happy Bow",
    description: "Graceful courteous bow of gratitude and achievement",
    action_instruction: "Character dips into a polite theatrical bow with modest happy smile, rising smoothly back to upright posture",
    energy_level: "moderate",
    loop_policy: "one_shot_rest",
    movement_intent: "courteous graceful accomplishment",
  },
];

export const ALL_RECIPES: readonly MascotAnimationRecipe[] = [...THINKING_RECIPES, ...CELEBRATE_RECIPES];
