/**
 * Matched in insertion order by substring, so specific domains (pets, dinosaurs, science) precede broader ones
 * (nature, school) that share vocabulary.
 */
export const CANONICAL_DOMAIN_KEYWORD_RULES: Record<string, string[]> = {
  anime_manga: ["anime", "manga", "otaku", "shonen", "ghibli", "naruto", "one piece", "dragon ball", "pokemon", "doraemon"],
  careers_occupations: [
    "career",
    "careers",
    "profession",
    "professions",
    "occupation",
    "occupations",
    "doctor",
    "police",
    "firefighter",
    "jobs",
  ],
  countries_nations: ["country", "countries", "nation", "nations", "geography", "flag", "flags", "capital", "landmark", "landmarks"],
  daily_objects: ["daily object", "household", "kitchen", "furniture", "tool", "appliance", "gadget"],
  dinosaurs_prehistoric: ["dinosaur", "dinosaurs", "prehistoric", "fossil", "fossils", "jurassic", "ice age", "t-rex"],
  festivals_cultures: [
    "festival",
    "festivals",
    "holiday",
    "holidays",
    "celebration",
    "tradition",
    "traditional clothing",
    "lunar new year",
  ],
  food_gastronomy: [
    "food",
    "dish",
    "dishes",
    "culinary",
    "cuisine",
    "cooking",
    "pastry",
    "ingredient",
    "ingredients",
    "chef",
    "recipe",
    "dessert",
  ],
  fruits_vegetables_plants: ["fruit", "fruits", "vegetable", "vegetables", "flower", "flowers", "plants", "trees", "garden", "botany"],
  gaming_esports: ["gaming", "esports", "video game", "video games", "nintendo", "playstation", "xbox", "gamer", "minecraft"],
  global_brands: ["brand", "brands", "company", "logo", "corporate", "iconic logo", "apple", "nike", "google"],
  human_body: ["body", "anatomy", "biology", "organ", "organs", "physiology", "human body", "health"],
  modern_cinema_tv: ["cinema", "movie", "movies", "film", "hollywood", "superhero", "marvel", "star wars", "pixar"],
  music_instruments_gear: ["music", "instrument", "instruments", "guitar", "piano", "drums", "audio", "gear"],
  mythology_creatures: ["myth", "mythology", "creature", "creatures", "legend", "folklore", "god", "gods", "monster", "dragon"],
  pets_farm_animals: ["pets", "puppy", "puppies", "kitten", "kittens", "dog breed", "cat breed", "farm animal", "farm animals", "barnyard"],
  nature_animals: ["animal", "animals", "wildlife", "nature", "mammal", "bird", "fish", "ocean", "predator", "safari", "forest"],
  places_facilities: ["place", "places", "facility", "facilities", "airport", "stadium", "hospital", "museum", "architecture"],
  pop_culture_classics: ["pop culture", "classic", "classics", "literature", "fairy tale", "retro", "cartoon", "cartoons"],
  science_how_things_work: [
    "experiment",
    "experiments",
    "physics",
    "chemistry",
    "inventor",
    "inventors",
    "scientist",
    "scientists",
    "how things work",
    "simple machine",
    "magnet",
    "gravity",
  ],
  school_learning: ["school", "learning", "classroom", "student", "teacher", "academy", "education", "math", "science"],
  space_earth: [
    "space",
    "earth",
    "planet",
    "planets",
    "astronomy",
    "cosmic",
    "cosmos",
    "solar system",
    "galaxy",
    "universe",
    "star",
    "stars",
  ],
  sports_games: ["sport", "sports", "football", "soccer", "basketball", "tennis", "olympics", "board game", "chess"],
  toys_playground: ["toys", "playground", "plaything", "outdoor games", "teddy bear"],
  vehicles_technology: [
    "vehicle",
    "vehicles",
    "car",
    "cars",
    "plane",
    "airplane",
    "aviation",
    "robot",
    "robotics",
    "tech",
    "technology",
    "ai",
  ],
};
